### ISSUE TITLE
EntityArc "flickers" downwards while holding it

### ISSUE THREAD

**Issue by CrowsOfWar** [ProjectKorra/AvatarMod#1]
When you hold a fire arc or a water arc, it "flickers" downwards every second or two, then goes back to its normal position.

Information obtained via `Thread.dumpStack()` in `EntityArc#setPosition` reveal that it has to do with Minecraft's packet system.

Further investigation required.

**Comment by CrowsOfWar** [comment]
I experienced a similar problem while creating the Fireball, but interestingly enough, the issue stopped when I changed `Vector.getEntityPos` to `Vector.getEyePos`. The issue is now only present with water arc.

**Comment by FavouriteDragon** [comment]
Doesn't happen with water arc anymore.
Happens with other entities such as floating block.

**Comment by FavouriteDragon** [comment]
Fixed for arcs
