### ISSUE TITLE
Only firebending/earthbending scrolls have recipes

### ISSUE THREAD

**Issue by Febilian** [ProjectKorra/AvatarMod#101]
Unsure if intended, but there seem to be no recipes for airbending or waterbending scrolls by default. I know they are obtainable through other means, but I just thought it was odd that fire/earth had recipes and nothing else.

**Comment by FavouriteDragon** [comment]
This is intended, as MC 1.12.2 doesn't have good items for these elements. This will change with 1.13 forge, as I'll be able to use hearts of the sea and phantom membranes.
