### ISSUE TITLE
Silly looking player-to-bison desync when riding a tamed bison on a server

### ISSUE THREAD

**Issue by Febilian** [ProjectKorra/AvatarMod#104]
![2018-12-20_01 31 23](https://user-images.githubusercontent.com/13922447/50276677-5f2b7600-03f7-11e9-93a7-a4e9bce25a40.png)

![2018-12-20_01 35 03](https://user-images.githubusercontent.com/13922447/50276725-7d917180-03f7-11e9-87cc-b9b1ee48bdc5.png)

As you can probably see, I'm like, eight feet above the bison. This remains consistently silly but may be varying heights above the bison while riding it.

Other than the issue of it being hard to see where I'm going while on my bison outside of a top-down view in third person, it works alright. Haven't tried taking passengers, though.

This happens with at least the studded bison saddle.

From what I can recall, other players have also mentioned being able to see this, so it's not just a clientside visual thing. I think my avatar is actually that distance above the bison while flying it.

**Comment by FavouriteDragon** [comment]
Yeah, you're actually that far above the bison. Woooopssss....
I'll see about adjusting this when I get back!

**Comment by Febilian** [comment]
Much obliged! :) Let me know if I should get more info or something.

**Comment by FavouriteDragon** [comment]
Can you see what other saddles are affected?
Thanks!

**Comment by Febilian** [comment]
It appears that in single player, every single saddle appears exactly the same, but with an _inverse_ problem: I'm more inside the bison than riding it, depending on which direction I'm looking/flying at the time.

![2018-12-23_16 47 44](https://user-images.githubusercontent.com/13922447/50388687-f54eed00-06d2-11e9-954e-baa15d90045c.png)
![2018-12-23_16 48 42](https://user-images.githubusercontent.com/13922447/50388688-fb44ce00-06d2-11e9-8823-328984afeb69.png)
![2018-12-23_16 48 39](https://user-images.githubusercontent.com/13922447/50388690-fed85500-06d2-11e9-90a7-50b5323f225c.png)

From what I recall, this is more or less what _originally_ happened on the server where I first noticed the problem, but as I was trying to figure out how bison controls worked, at some point my character ended up far above the bison and stayed there between sessions.

**Comment by FavouriteDragon** [comment]
o_0
I'll need to take a look at this...
Thanks!

**Comment by FavouriteDragon** [comment]
Ok so, I know we've been unable to resolve it, but now we have more info- apparently the bison has to be *completely* grown for this to happen. Our mob dev is looking at this over the next couple weeks or so, along with numerous other bison changes!

**Comment by Febilian** [comment]
Nice! Here's to hoping this can be resolved soonish, then.

**Comment by Jackiecrazy** [comment]
I get another issue with it: the bison's model, except for the body, disappears, and the server freezes while the client continues running. Also happens with ostrich horses.

**Comment by SangurianSoul** [comment]
Not to spam any messages or anything, but i do want to point out that this is still an issue.

i know there hasn't been an update in some time, but i just wanted to share that my friends also have this problem still.

**Comment by FavouriteDragon** [comment]
Fixed in the next update
