### ISSUE TITLE
Crash with element arc

### ISSUE THREAD

**Issue by KeiLibrarium** [ProjectKorra/AvatarMod#106]
hey,
I have a problem with the arc of all element, I crash ! 
My log : https://pastebin.com/QwenPE9R

**Comment by FavouriteDragon** [comment]
Update your Java version to 181, and upgrade your graphics drivers.

**Comment by KeiLibrarium** [comment]
I have update Java and my drivers, and i crash with arc of element TwT
Log : https://pastebin.com/kFVrRPwR

**Comment by Mahtaran** [comment]
Could you try with the thin JAR and the library manually added to the `mods` folder?
They library can be found [here](https://github.com/ProjectKorra/AvatarMod/blob/master/libs/yaml/snakeyaml-1.16.jar)
The thin JAR can be obtained by download the [OldPackets tree](https://github.com/ProjectKorra/AvatarMod/tree/FD/OldPackets) and executing the relevant build script (`build unix.sh` or `build windows.bat`), and then going to the `build/libs` folder (note: `build`, not `builds`)

**Comment by FavouriteDragon** [comment]
Remove Africacraft from your mods folder- for some reason, it causes the crash. Dunno why

**Comment by FavouriteDragon** [comment]
Sorry, Agricraft, not Africacraft.

**Comment by KeiLibrarium** [comment]
Hello ! i'm sorry, but i crash again... 
Logs : https://pastebin.com/4gn5B1Cw
It's only Arc element, the other power it's ok, i have remove Agricraft, and i have try with the THIN.jar and the library in the mods folder..

**Comment by Mahtaran** [comment]
Oh no you should only do one of the two, not both at the same time.

**Comment by FavouriteDragon** [comment]
That's ok!
Yes, please try with just avatar.

**Comment by KeiLibrarium** [comment]
Just with Avatar it"s okey, so... conflit with a mod ?

**Comment by Mahtaran** [comment]
If it works without AgriCraft, then yes, that is a mod conflict.

Si ça marche sans AgriCraft, c’est bien un conflicte entre les deux mods.

**Comment by KeiLibrarium** [comment]
Hum..... It's not Agricraft, but this library : InfinityLib.. I have test Avatar with all others mods, one per one, and it's this lib

**Comment by Mahtaran** [comment]
This is fixed as of [1.5.10-alpha](https://minecraft.curseforge.com/projects/avatar-mod-2-out-of-the-iceberg/files/2663021).
