### ISSUE TITLE
Crash with reliquary because pedistals can't be benders.

### ISSUE THREAD

**Issue by Divineaspect** [ProjectKorra/AvatarMod#107]
https://gist.github.com/Divineaspect/b16b7c8713cc834ff9bf22791bca98c8

This is making the pedestals from reliquary, a major source of automation, unusable.

**Comment by Stv13579** [comment]
I've been encountering the same issue, but with the Extra Utilities automated user. I'm pretty sure it is also causing issues with the Cyclic one as well, though I've only seen major tps drops from it rather than full on crashes.

**Comment by FavouriteDragon** [comment]
Why am I so bad at time management? This will be fixed tonight and there'll be a release.
*I'm sorrrrryyyyyy*

**Comment by FavouriteDragon** [comment]
Fixed, I just have to repair my dev environment to get it out- I'm planing on update some particle effects as well.
