### ISSUE TITLE
Crash when calling cloudburst in Deeplands (AoA)

### ISSUE THREAD

**Issue by Jackiecrazy** [ProjectKorra/AvatarMod#108]
No idea why it'd do that, but world is corrupted now.
https://pastebin.com/zy4mHDRm

**Comment by FavouriteDragon** [comment]
Yeah, it seems to crash the nether too, but I'm not sure if that's related. I'll take a look tonight.

**Comment by FavouriteDragon** [comment]
Fixed (hopefully)
