### ISSUE TITLE
Black screen when using slipstream?

### ISSUE THREAD

**Issue by someoneenoemos** [ProjectKorra/AvatarMod#115]
I'm pretty sure this isn't just me, as I have seen other people say things about it. What happens is just when I use the slipstream skill it makes my screen go all black.

**Comment by FavouriteDragon** [comment]
Yeah this is a known bug- it's a shader issue, and will be fixed in the rewrite. We're not sure why this happens, but it does.

**Comment by FavouriteDragon** [comment]
We're adding a config for this, with shaders disabled by default. This way it won't turn your screen black.

**Comment by Aang23** [comment]
Also, what's your OS / GPU / GPU driver version ? (F3 screenshot)
I'll try fixing them later, and those infos may help me. For now this is a Windows-only bug as far as I know.

**Comment by Jackiecrazy** [comment]
Confirmed on a mac as well. It just randomly started happening for me.

**Comment by FavouriteDragon** [comment]
Still haven't figured out a way to fix this, I'm assuming it's related to how some shaders aren't supported by mac and intel gpus.
As shaders are disabled by default, I'm closing this, as only those with Nvidia gpus will turn them on.
