### ISSUE TITLE
Bending not restarting

### ISSUE THREAD

**Issue by GabbNicoh** [ProjectKorra/AvatarMod#117]
Every time i make a new world my previous bending keys start to make me bend even though i am not a bender yet. For example in my previous world i was a fire bender, then in the new world that i made even though i haven't started learning some scrolls i already have the traits/bending skills form the previous world. As of the moment i have not found a solution to the bug, so if anyone can help me it would mean a lot thanks!

**Comment by FavouriteDragon** [comment]
Yeah this is a known bug, it'll be fixed in the rewrite.
