### ISSUE TITLE
Mod prevents minecraft from launching

### ISSUE THREAD

**Issue by hueflungusblungus** [ProjectKorra/AvatarMod#120]
When I try to launch minecraft with the avatar mod, it crashes and says "There was a severe problem during mod loading that has caused the game to fail." This doesn't happen when the mod isn't in the mod folder. Crash report here: https://pastebin.com/hAnZkjdv

**Comment by FavouriteDragon** [comment]
Try removing llibrary and see if the issue persists. Also try deleting the config folder.

**Comment by hueflungusblungus** [comment]
Hmm, that didn't seem to stop the crashing. I deleted the llibrary and the dragon mounts mod (because it depends on the llibary mod) and the config folder and it continues having the error.

**Comment by hueflungusblungus** [comment]
New crash report: https://pastebin.com/m7VbfCfz

**Comment by FavouriteDragon** [comment]
Ok so there's no reason why this should be happening. This is the only case of this crash. Maybe
-Make sure you're in online mode/connected to the internet
-Allocate more ram
-Use 64 bit java 181+
-Downgrade forge to 2768

**Comment by FavouriteDragon** [comment]
Ah- yeah the problem is forge. Change it to 2838 or 2768.
