### ISSUE TITLE
Significant log spam when Fake Players are trying to right click anything

### ISSUE THREAD

**Issue by thephoenixlodge** [ProjectKorra/AvatarMod#122]
I added the mod to the pack I'm working on, and when I loaded it up, noticed the game was lagging significantly. Upon checking the log, the lag was due to a big error occurring every time a nearby golem from Thaumcraft tried to right click an item into an Astral Sorcery Lightwell. This error did not occur before I added Avatar 2, and the mod is directly called out in the error message.
What I guess seems to be happening is that Avatar 2 is checking whether the player knows a specific bending style, but failing to consider that fake players can right click things, so when it trys to get the fake player's data from it's UUID, it fails as fake players don't have UUIDs as they aren't actual minecraft accounts.
Even more frustrating, the error results in the right click event getting outright cancelled, so fake players becomes unable to do any right click actions.

Error: https://pastebin.com/1nNdhWui

**Comment by Aang23** [comment]
Again... @FavouriteDragon we might want to partially rewrite the BendingData storage system after all...

**Comment by FavouriteDragon** [comment]
I honestly don't know what else to do, considering I'm checking for everything, including a UUID....

**Comment by FavouriteDragon** [comment]
Yeah we're rewriting it, but this bug is annoying

**Comment by FavouriteDragon** [comment]
Oh wow I'm literally stupid I just fixed it
It'll be out in the next update!

**Comment by thephoenixlodge** [comment]
Can I expect that update anytime soon? This is a rather problematic bug, so to have already been waiting months for the fix to be released is concerning.

**Comment by FavouriteDragon** [comment]
Sorry, it's not that the bug is hard to fix, it's that we're doing one massive update with lots of brand new content and a rewritten progression system :P
Our update should be out late January, though we could get it out in December depending on how much time Aang has.
