### ISSUE TITLE
Game crashes when i join a world

### ISSUE THREAD

**Issue by WhiteSlayer** [ProjectKorra/AvatarMod#124]
there are no other mods in the mod file , did everything like the video's etc.. looks fine to me but it keeps crashing same with my friend :/

**Comment by Aang23** [comment]
Crash report / Logs ?
Forge version ?
Java version ?

**Comment by FavouriteDragon** [comment]
It's probably because your forge version isn't 2838.

**Comment by FavouriteDragon** [comment]
No word from the user, so I'm closing this.
