### ISSUE TITLE
[1.12.2]Crash upon trying to Dial RFTools Dimension

### ISSUE THREAD

**Issue by Secretname2009** [ProjectKorra/AvatarMod#125]
This might be a conflict with RFTools as whenever i try to dial a dimension that is created through RFTools then it suddenly crashes. This basically prevents me from accessing the main part of that mod and the crashlog mentions this mod.
VanillaFix prevented it from crashing to desktop but it ends up never dialing the dimension at all.

[crash-2019-07-19_21.28.43-client.txt](https://github.com/ProjectKorra/AvatarMod/files/3412484/crash-2019-07-19_21.28.43-client.txt)

**Comment by Aang23** [comment]
Thanks for reporting!

**Comment by FavouriteDragon** [comment]
Well, I don't know if I fixed it, but I might've helped.
This sounds like an issue with how minecraft and we store data.
Yay.
_This is why we're gonna rewrite the mod_

**Comment by Mahtaran** [comment]
Closed due to inactivity. Reopen if the bug still exists.
