### ISSUE TITLE
Crashing when riding a Sky Bison, I have several mods with it

### ISSUE THREAD

**Issue by Nues** [ProjectKorra/AvatarMod#128]
[crash-2019-07-29_15.57.40-client.txt](https://github.com/ProjectKorra/AvatarMod/files/3444102/crash-2019-07-29_15.57.40-client.txt)

I tend to crash while riding an Sky Bison in under a minute, although not instantly.

It was apparently due to a ticking entity issue, but there should be a crash log pasted here for more information.

I have the following mods besides Avatar 2 Mod - Out Of the Iceberg:

CubicChunks by barteks2x
CubicChunksWorldGen by barteks2x
Yoyos by JozuFozu
Spartan Weaponry by ObliviousSpartan
Spartan Shields by ObliviousSpartan
Xaeros WorldMap by Xaeros96

I installed Java 8 - Update 211 and Forge's latest 1.12.2 (which ends with 14.23.5.2838) to make sure it wasn't because of old versions.

Let me know if the pasted crash file is uploaded, since I am very new here.

EDIT: I am using the latest version of AvatarMod.

**Comment by FavouriteDragon** [comment]
This is an incompatibility with CubicChunks- you're going to have to remove them for now. It's due to Crows making the bison force load chunks when you log back on a world.

**Comment by FavouriteDragon** [comment]
Ok this will be fixed in the next update
