### ISSUE TITLE
Mods preventing minecraft from launching

### ISSUE THREAD

**Issue by FrozenAssassin17** [ProjectKorra/AvatarMod#129]
every time I try to launch Minecraft I get this message "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail".
I have forge 2838.
and the required Java 8 (181)
a link to the code: https://pastebin.com/aBtbNq0y
someone, please help this is hurting my brain.

**Comment by Mahtaran** [comment]
Did you edit your configuration file? If so, could you send it?

**Comment by FavouriteDragon** [comment]
Update your mod version :P
