### ISSUE TITLE
[Question] Avatar Mod 2: Out of the Iceberg connection problem

### ISSUE THREAD

**Issue by KuroaHit** [ProjectKorra/AvatarMod#131]
I would like to ask about the MOD problem. I used FORGE to set up the MOD server. But after installing this mod, the only moves in it are that I can learn. Other players can't learn. I would like to ask what is the reason and the solution. Please answer the questions from MOD experts. Thank you.

**Comment by Mahtaran** [comment]
Hi. Is there anything out of the ordinary in the logs? Did you try giving them bending via the command?

**Comment by KuroaHit** [comment]
Just give them three reels, they press ALT or show no learning. I also tried to give them skills with instructions, but they still can't use them.

**Comment by Mahtaran** [comment]
What command did you use?

**Comment by KuroaHit** [comment]
I also tried other versions, but I still have the same solution. I can only learn from others. Other people can't learn.

**Comment by Mahtaran** [comment]
Could you send your log?

**Comment by KuroaHit** [comment]
How can I send it? Sorry, I don’t know where the log is.

**Comment by Mahtaran** [comment]
It is located in the `logs` directory. It would be great if you could send the `latest.log` and `debug.log` (if present) files.

**Comment by KuroaHit** [comment]
[latest.log](https://github.com/ProjectKorra/AvatarMod/files/3714085/latest.log)
[debug.log](https://github.com/ProjectKorra/AvatarMod/files/3714086/debug.log)

**Comment by KuroaHit** [comment]
Uploaded, please.

**Comment by Mahtaran** [comment]
Could you try giving one of the players bending with the command (they must be online) and have them try unlocking bending after that, and send me the logs afterwards?

**Comment by KuroaHit** [comment]
Does it mean that they are given skills on the line with instructions?

**Comment by KuroaHit** [comment]
If so, I just tried it, but still the same. They are online, but I am giving instructions to them but they still can’t use them.

**Comment by KuroaHit** [comment]
[debug.log](https://github.com/ProjectKorra/AvatarMod/files/3714360/debug.log)
[latest.log](https://github.com/ProjectKorra/AvatarMod/files/3714362/latest.log)

**Comment by KuroaHit** [comment]
This is the log after the try. Please, please.

**Comment by Mahtaran** [comment]
What does the command return (in the chat)?

**Comment by KuroaHit** [comment]
作者你好

**Comment by KuroaHit** [comment]
> Hello author

**Comment by KuroaHit** [comment]
I don't quite understand what you mean. Which instruction?

**Comment by KuroaHit** [comment]
This is the result of the new test. Please look at it. Please.
[debug.log](https://github.com/ProjectKorra/AvatarMod/files/3721477/debug.log)
[latest.log](https://github.com/ProjectKorra/AvatarMod/files/3721478/latest.log)

**Comment by FavouriteDragon** [comment]
Hmm I can't see anything in there. Did you use commands to try to give yourself bending?

**Comment by FavouriteDragon** [comment]
Try updating to windows 10?

**Comment by ErAmoJS** [comment]
Helllo i guess i have the same problema of KuroaHit.. im playing on a lan server with my brother and he can't learn bending, cant with scrolls and cant with admin comands. We try without all other mods and still dont working.. idk what happen or is a problem of the version.. he cant see the skill menú. and cant see the cube that shows the element in the screen

**Comment by FavouriteDragon** [comment]
Make sure your server is online mode, you've all bought minecraft, and that your forge version is 2838+. Also try deleting your playerdata and a new installation of the mod.

**Comment by ErAmoJS** [comment]
Hi, we are playing in lan local server no online and try everything..
nothing works. It must be an mod error because is the unique problem that
we have playing, the unique mod that have a problem

**Comment by FavouriteDragon** [comment]
LAN servers are pretty buggy with the mod, it's better to use a dedicated server.

**Comment by FavouriteDragon** [comment]
And you should have a world-options file or something like that. Make sure cracked accounts are disabled and that you're all using valid mc accounts.

**Comment by XxsjrapsxX** [comment]
I have a dedicated server setup via my friend, we are using the latest version of forge and the mod. The results we get from trying to learn bemding is quite perculiare, do you mind if i record what is going on and send it to you as a gif or a video?

**Comment by FavouriteDragon** [comment]
Sure!

**Comment by XxsjrapsxX** [comment]
https://youtu.be/V4U-5dx-ZYc
also here is a more detailed version of what happened when i joined the game on my friends server
https://cdn.discordapp.com/attachments/717225014688219179/718653071399452682/unknown.png

**Comment by Calebzaw** [comment]
Having literally the same problem that was shown on the video, is there a fix?

**Comment by lukenator115** [comment]
Also having this issue - the issue in the video is the LAN issue as well

**Comment by Mahtaran** [comment]
Alright, we will investigate this further, but I am going to need some basic information.

First off, try on a truly dedicated server. Not a LAN server, not some Hamachi stuff, not an Aternos server, but a truly dedicated server either on a known host or on a port forwarded, statically addressed machine.

Secondly, make sure both the server and players are running plain old Forge via the default launcher (not MultiMC, just to be sure). So no SpongeForge or patched Forge with OptiFine or other CoreMods or whatever.

Next up, I am going to need, for both the server and all players (the minimum required amount to reproduce the bug, probably one or two):
- Java version
- Forge version
- Mod version
- Full mod list
- Debug and normal log files

Yes, that is a lot, but the more information we have the easier it becomes to solve problems, so I hope you can understand. If you for whatever reason feel uncomfortable sharing this information online, send them via email at [mahtaran@amuzil.com](mailto:mahtaran@amuzil.com) or in a Discord DM.

**Comment by lukenator115** [comment]
Works fine, it's just a LAN thing

**Comment by Nat-J-Greywater** [comment]
ive been using this mod in the most current version of the rogue-like dungeons modpack on twitch (I added in the latest avatar mod version), and I've noticed several bending abilities just stopped working. so far I've found that the: air jump, fire jump, slipstream fly, and the earth dig, abilities won't work at all and I can't figure out why. (also the symbols that show that say the air jump ability is active, next to the crosshair, won't go away while the mod is installed)

I was told to send the forge and java versions I've been using, the latest log and the mods used so here you go:https://docs.google.com/document/d/1lUq03VOjj-kKcWyUH9zZ2tZZffEqmXTdyBMlSG-xAPE/edit?usp=sharing
here's a google doc with all the mods and version stuff and the latest log is below
[latest.log](https://github.com/ProjectKorra/AvatarMod/files/5106119/latest.log)
lemme know if there's anything else I can send that may help!!

**Comment by Mahtaran** [comment]
@Nat-J-Greywater could you open a new ticket for your issue?

**Comment by Bothi2009** [comment]
А где взять свиток магии молнии?

**Comment by Jasheenshrey** [comment]
I do the command add bending but it doesn't appear but says it was added. I can't find it. What should I do.

**Comment by HasanDf** [comment]
If someone found the solution please tell me I have the problem
