### ISSUE TITLE
Crash with Right-Click Issue with Cyclic's Forester (entity without an UUID)

### ISSUE THREAD

**Issue by tetrathegreat** [ProjectKorra/AvatarMod#132]
So, whenever I put saplings in my Cyclic Forester for it to plant the trees, my server crashes. Looking at the logs, it indicates this mod as the culprit and it has to deal with right click behavior.

```
Description: Ticking block entity

java.lang.IllegalArgumentException: Can't get data for an entity without an UUID
    at com.crowsofwar.avatar.common.data.BendingData.get(BendingData.java:82)
    at com.crowsofwar.avatar.common.IceActionCanceller.isTrapped(IceActionCanceller.java:46)
    at com.crowsofwar.avatar.common.IceActionCanceller.onInteract(IceActionCanceller.java:63)
...

-- Block entity being ticked --
  Name: minecraft:block_forester_te // com.lothrazar.cyclicmagic.block.forester.TileEntityForester
```

**Comment by FavouriteDragon** [comment]
Hmm- I'll try to get on this as soon as possible. I've done some temporary fixes, but I'll need to go through the code and fix every instance of this. It'll be in the next update!

**Comment by ewanm89** [comment]
Related: https://github.com/ProjectKorra/AvatarMod/issues/122
