### ISSUE TITLE
Non opening world

### ISSUE THREAD

**Issue by KACD-Sp** [ProjectKorra/AvatarMod#133]
At first the game works ok, but when you try to open a world in most cases it closes with the game itself.
An error messaje appears and I don´t know what it means or how to solve the problem: 

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

**Comment by Vexii950** [comment]
Same

**Comment by FavouriteDragon** [comment]
Update your forge versions to 2838
