### ISSUE TITLE
crashing with other mods

### ISSUE THREAD

**Issue by ISAK-SWE05** [ProjectKorra/AvatarMod#134]
[crash-2020-01-22_08.59.11-client.txt](https://github.com/ProjectKorra/AvatarMod/files/4093564/crash-2020-01-22_08.59.11-client.txt)
not sure if its avatar mod thats the problem

**Comment by FavouriteDragon** [comment]
Can you tell me what you were doing when this happened?

**Comment by ISAK-SWE05** [comment]
it started when i choose an element so i removed my element and it was normal again

**Comment by ISAK-SWE05** [comment]
now without changing anything i cant join the server at all



[crash-2020-01-23_11.52.13-client.txt](https://github.com/ProjectKorra/AvatarMod/files/4100438/crash-2020-01-23_11.52.13-client.txt)

**Comment by ISAK-SWE05** [comment]
i just tested creating a new world to test but it worked fine
maybe its the server?
but the server never crashed

**Comment by FavouriteDragon** [comment]
Do buy mc or do you have a cracked account?

**Comment by FavouriteDragon** [comment]
Oh try updating your java version to 181 or higher

**Comment by FavouriteDragon** [comment]
This should be fixed now, will be in the next update

**Comment by ISAK-SWE05** [comment]
i have a premium account just that the server is on offline mode so i can join while no internet and i got the latest java k thx
