### ISSUE TITLE
Optifine + avatar mod glitch

### ISSUE THREAD

**Issue by franco0882** [ProjectKorra/AvatarMod#136]

**Comment by franco0882** [comment]
Avatar mod is not working with optifine 1.12.2 it is glitching my guis out and making them disappear and then after a bit... it crashes if there is any way you can help me with that i would greatly appreciate it.

**Comment by FavouriteDragon** [comment]
Try updating optifine to the latest version.
Also, try resetting your visual settings and systematically try each 1.12.2 version until it works.
