### ISSUE TITLE
Ticking Entity crash with Fish's Undead rising mod

### ISSUE THREAD

**Issue by frostfire50** [ProjectKorra/AvatarMod#138]
So I had air bending and I was using the air blade move the last version dragon claw I hit one of the creatures from the other mod the undead swine then I crashed it doesn't happen to any other mob from what I know of also I sent the same issue to the author of the other mod because I dont know which mod is causing it and here's the crash report
https://paste.dimdev.org/wobayapoyu.mccrash

edit:so it seems like any of the air bending move crash when interacting with the undead swine I will test if other bending crash with the mob

edit 2:so after experimenting and many crashes it seems like most abilities crash when interact with the mob but not all of the abilities

**Comment by FavouriteDragon** [comment]
That's an issue on their side, but I'll still look into it.
