### ISSUE TITLE
ticking entity players

### ISSUE THREAD

**Issue by DancingTillDead** [ProjectKorra/AvatarMod#140]
So I'm on mac playing on a server with the avatar mod and I've had this problem where whenever I get into the server my game crashes and it's always because of a ticking entity and it's always another player. I've reinstalled java multiple times and restarted my computer multiple times and I've tried different versions and all versions below and 5.9 preview 5 all work so I'm thinking something with the newer versions broke something. but anyway heres the crash report. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  McLib core mod (mclib-1.0.4-1.12.2.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 4/13/20 12:02 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Can't get data for an entity without an UUID
	at com.crowsofwar.avatar.common.data.BendingData.get(BendingData.java:82)
	at com.crowsofwar.avatar.common.data.ctx.PlayerBender.getData(PlayerBender.java:57)
	at com.crowsofwar.avatar.common.AvatarPlayerTick.onPlayerTick(AvatarPlayerTick.java:37)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_15_AvatarPlayerTick_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190)
	at net.minecraft.client.entity.EntityOtherPlayerMP.func_70071_h_(EntityOtherPlayerMP.java:63)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.crowsofwar.avatar.common.data.BendingData.get(BendingData.java:82)
	at com.crowsofwar.avatar.common.data.ctx.PlayerBender.getData(PlayerBender.java:57)
	at com.crowsofwar.avatar.common.AvatarPlayerTick.onPlayerTick(AvatarPlayerTick.java:37)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_15_AvatarPlayerTick_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190)
	at net.minecraft.client.entity.EntityOtherPlayerMP.func_70071_h_(EntityOtherPlayerMP.java:63)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityOtherPlayerMP)
	Entity ID: 125
	Entity Name: AidanJett
	Entity's Exact location: 2119.20, 2.00, 559.24
	Entity's Block location: World: (2119,2,559), Chunk: (at 7,0,15 in 132,34; contains blocks 2112,0,544 to 2127,255,559), Region: (4,1; contains chunks 128,32 to 159,63, blocks 2048,0,512 to 2559,255,1023)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['EggrollDoinks'/573561, l='MpServer', x=8.50, y=65.00, z=8.50], EntityOtherPlayerMP['AidanJett'/125, l='MpServer', x=2119.20, y=2.00, z=559.24]]
	Chunk stats: MultiplayerChunkCache: 250, 250
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 19 game time, 19 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 129 total; [ZombieSoldier['Zombie Soldier'/573449, l='MpServer', x=2091.13, y=64.00, z=588.55], EntityBat['Bat'/569358, l='MpServer', x=2044.75, y=42.06, z=553.56], EntityCreeper['Creeper'/573447, l='MpServer', x=2080.50, y=77.00, z=534.50], ZombieMiner['Zombie Miner'/570911, l='MpServer', x=2094.28, y=77.00, z=545.82], EntityBat['Bat'/573460, l='MpServer', x=2133.59, y=11.63, z=514.50], EntityBat['Bat'/573205, l='MpServer', x=2098.43, y=19.00, z=508.94], EntityBat['Bat'/573206, l='MpServer', x=2131.45, y=39.04, z=612.69], SkeletonSoldier['Skeleton Soldier'/570922, l='MpServer', x=2105.50, y=77.00, z=554.50], ZombieSoldier['Zombie Soldier'/572449, l='MpServer', x=2122.50, y=47.00, z=538.50], ZombieMiner['Zombie Miner'/572451, l='MpServer', x=2121.50, y=47.00, z=536.50], EntityBat['Bat'/546339, l='MpServer', x=2115.25, y=10.10, z=530.55], ZombieFarmer['Zombie Farmer'/572454, l='MpServer', x=2123.50, y=47.00, z=541.50], EntityBat['Bat'/573233, l='MpServer', x=2120.34, y=22.40, z=493.64], EntityBat['Bat'/571699, l='MpServer', x=2120.75, y=45.10, z=535.75], EntityBat['Bat'/571700, l='MpServer', x=2119.04, y=42.45, z=521.65], EntityBat['Bat'/573237, l='MpServer', x=2126.83, y=36.09, z=564.94], Bandit['Bandit'/572470, l='MpServer', x=2081.50, y=80.00, z=640.50], ZombieSoldier['Zombie Soldier'/573256, l='MpServer', x=2052.50, y=20.00, z=547.50], EntityCreeper['Creeper'/571464, l='MpServer', x=2073.50, y=30.00, z=512.50], EntityCreeper['Creeper'/571465, l='MpServer', x=2074.50, y=30.00, z=509.50], ZombieMiner['Zombie Miner'/573258, l='MpServer', x=2050.50, y=20.00, z=548.50], SkeletonSoldier['Skeleton Soldier'/573260, l='MpServer', x=2051.50, y=20.00, z=549.50], EntityCreeper['Creeper'/570435, l='MpServer', x=2058.50, y=59.00, z=530.50], EntityCreeper['Creeper'/570436, l='MpServer', x=2059.50, y=58.00, z=528.30], EntityBat['Bat'/569669, l='MpServer', x=2078.75, y=37.10, z=494.58], ZombieMiner['Zombie Miner'/573254, l='MpServer', x=2053.50, y=20.00, z=545.50], EntitySkeleton['Skeleton'/571992, l='MpServer', x=2107.50, y=72.00, z=499.50], ZombieFarmer['Zombie Farmer'/571990, l='MpServer', x=2053.50, y=78.00, z=554.50], EntitySkeleton['Skeleton'/573547, l='MpServer', x=2065.50, y=74.00, z=545.50], EntityCreeper['Creeper'/573549, l='MpServer', x=2066.50, y=74.00, z=543.50], EntityCreeper['Creeper'/573550, l='MpServer', x=2066.50, y=74.00, z=544.50], EntityZombie['Zombie'/573024, l='MpServer', x=2041.50, y=73.00, z=487.50], ZombieFarmer['Zombie Farmer'/572005, l='MpServer', x=2115.50, y=71.00, z=634.50], SkeletonSoldier['Skeleton Soldier'/571495, l='MpServer', x=2107.38, y=77.00, z=560.75], EntityZombie['Zombie'/572280, l='MpServer', x=2102.50, y=44.00, z=630.50], ZombieFarmer['Zombie Farmer'/569209, l='MpServer', x=2107.49, y=39.00, z=514.80], EntityWitch['Witch'/572281, l='MpServer', x=2115.27, y=46.00, z=634.50], EntityBat['Bat'/470900, l='MpServer', x=2131.75, y=22.10, z=539.53], EntityPlayerSP['EggrollDoinks'/573561, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unknown'/123, l='MpServer', x=8.50, y=65.00, z=8.50], EntityOtherPlayerMP['AidanJett'/125, l='MpServer', x=2119.20, y=2.00, z=559.24], ZombieFarmer['Zombie Farmer'/573559, l='MpServer', x=2097.50, y=38.00, z=521.50], EntityZombie['Zombie'/572279, l='MpServer', x=2104.50, y=44.00, z=632.50], ZombieFarmer['Zombie Farmer'/573322, l='MpServer', x=2047.50, y=74.00, z=592.50], ZombieMiner['Zombie Miner'/486784, l='MpServer', x=2125.30, y=23.18, z=554.70], EntitySentry['Sentry'/466575, l='MpServer', x=2030.50, y=58.00, z=554.50], EntitySentry['Sentry'/466570, l='MpServer', x=2023.50, y=58.00, z=576.50], ZombieMiner['Zombie Miner'/571782, l='MpServer', x=2102.50, y=78.00, z=526.50], EntityLlama['Llama'/466056, l='MpServer', x=2050.50, y=73.00, z=541.42], EntitySentry['Sentry'/466583, l='MpServer', x=2023.50, y=58.00, z=575.50], EntitySentry['Sentry'/466582, l='MpServer', x=2023.50, y=58.00, z=568.50], SkeletonSoldier['Skeleton Soldier'/571801, l='MpServer', x=2084.50, y=67.00, z=621.50], EntityLlama['Llama'/466070, l='MpServer', x=2120.65, y=74.00, z=528.91], EntitySentry['Sentry'/466581, l='MpServer', x=2023.50, y=58.00, z=569.50], EntityLlama['Llama'/466069, l='MpServer', x=2095.12, y=77.00, z=546.57], EntitySentry['Sentry'/466580, l='MpServer', x=2028.50, y=58.00, z=567.50], EntitySkeleton['Skeleton'/573339, l='MpServer', x=2094.50, y=13.00, z=497.50], EntitySentry['Sentry'/466579, l='MpServer', x=2030.50, y=58.00, z=565.50], EntitySentry['Sentry'/466578, l='MpServer', x=2028.50, y=58.00, z=565.50], Bandit['Bandit'/573341, l='MpServer', x=2093.50, y=13.00, z=496.50], EntityZombie['Zombie'/573086, l='MpServer', x=2049.50, y=78.00, z=554.50], EntitySentry['Sentry'/466576, l='MpServer', x=2028.50, y=58.00, z=554.50], EntityBat['Bat'/496784, l='MpServer', x=2119.75, y=5.10, z=529.25], EntitySpider['Spider'/573584, l='MpServer', x=2059.50, y=76.00, z=559.50], EntitySkeleton['Skeleton'/573587, l='MpServer', x=2059.50, y=76.00, z=557.50], EntitySentry['Sentry'/466584, l='MpServer', x=2030.50, y=58.00, z=567.50], EntityZombie['Zombie'/573096, l='MpServer', x=2110.50, y=76.00, z=491.50], EntityPainting['Painting'/465831, l='MpServer', x=2120.00, y=8.50, z=560.97], ZombieFarmer['Zombie Farmer'/572073, l='MpServer', x=2107.50, y=31.00, z=496.50], EntityWitch['Witch'/572842, l='MpServer', x=2110.50, y=55.00, z=529.50], EntityWitch['Witch'/572843, l='MpServer', x=2108.50, y=55.00, z=528.50], EntityWitch['Witch'/572844, l='MpServer', x=2109.50, y=57.00, z=524.73], EntityLlama['Llama'/466082, l='MpServer', x=2128.24, y=80.00, z=579.85], EntitySentry['Sentry'/466593, l='MpServer', x=2037.50, y=58.00, z=567.50], EntitySentry['Sentry'/466592, l='MpServer', x=2035.50, y=58.00, z=567.50], EntityLlama['Llama'/466095, l='MpServer', x=2102.41, y=74.00, z=586.50], EntityLlama['Llama'/466606, l='MpServer', x=2089.60, y=72.00, z=503.50], EntityVehicleG_Car['entity.vehiclecar.name'/466094, l='MpServer', x=2104.00, y=78.47, z=526.00], EntityArmorStand['Armor Stand'/466093, l='MpServer', x=2091.50, y=6.00, z=538.50], EntityLlama['Llama'/465837, l='MpServer', x=2123.37, y=77.00, z=563.37], EntityPainting['Painting'/465836, l='MpServer', x=2118.50, y=8.50, z=560.97], EntityArmorStand['Armor Stand'/466091, l='MpServer', x=2098.50, y=64.00, z=691.50], EntityPainting['Painting'/465835, l='MpServer', x=2117.50, y=8.00, z=560.97], EntityPainting['Painting'/465834, l='MpServer', x=2119.50, y=6.50, z=560.97], ZombieMiner['Zombie Miner'/573094, l='MpServer', x=2122.17, y=75.00, z=500.27], EntityPainting['Painting'/465833, l='MpServer', x=2120.50, y=6.50, z=560.97], EntityPainting['Painting'/465832, l='MpServer', x=2118.00, y=6.50, z=560.97], ZombieSoldier['Zombie Soldier'/572856, l='MpServer', x=2054.72, y=73.00, z=516.50], ZombieMiner['Zombie Miner'/572600, l='MpServer', x=2113.50, y=60.00, z=517.50], EntityItemFrame['entity.ItemFrame.name'/466103, l='MpServer', x=2120.97, y=7.50, z=557.50], EntityItemFrame['entity.ItemFrame.name'/466102, l='MpServer', x=2120.97, y=7.50, z=556.50], ZombieFarmer['Zombie Farmer'/572602, l='MpServer', x=2112.50, y=60.00, z=515.50], EntitySkeleton['Skeleton'/573371, l='MpServer', x=2042.50, y=41.00, z=530.50], ZombieFarmer['Zombie Farmer'/571835, l='MpServer', x=2051.50, y=72.00, z=529.50], Bandit['Bandit'/570034, l='MpServer', x=2093.50, y=45.00, z=604.50], EntityLlama['Llama'/466108, l='MpServer', x=2123.90, y=77.00, z=550.48], ZombieFarmer['Zombie Farmer'/572596, l='MpServer', x=2109.84, y=60.00, z=511.60], EntityItemFrame['entity.ItemFrame.name'/466107, l='MpServer', x=2120.97, y=7.50, z=558.50], EntitySkeleton['Skeleton'/572853, l='MpServer', x=2060.50, y=75.00, z=522.50], EntityVehicleG_Car['entity.vehiclecar.name'/466106, l='MpServer', x=2119.33, y=5.38, z=557.59], ZombieMiner['Zombie Miner'/572598, l='MpServer', x=2113.50, y=60.00, z=516.50], EntityArmorStand['Armor Stand'/466105, l='MpServer', x=2124.50, y=10.00, z=554.50], EntityItemFrame['entity.ItemFrame.name'/466104, l='MpServer', x=2115.03, y=8.50, z=557.50], EntitySquid['Squid'/572110, l='MpServer', x=2075.85, y=60.98, z=602.22], EntitySquid['Squid'/572111, l='MpServer', x=2077.81, y=61.68, z=608.46], ZombieFarmer['Zombie Farmer'/572633, l='MpServer', x=2143.50, y=74.00, z=514.50], EntityZombie['Zombie'/573147, l='MpServer', x=2060.50, y=73.00, z=491.50], ZombieFarmer['Zombie Farmer'/572635, l='MpServer', x=2053.79, y=73.00, z=518.38], ZombieFarmer['Zombie Farmer'/573149, l='MpServer', x=2072.50, y=73.00, z=628.50], ZombieMiner['Zombie Miner'/572638, l='MpServer', x=2064.50, y=75.00, z=509.50], EntityOtherPlayerMP['AidanJett'/125, l='MpServer', x=2119.20, y=2.00, z=559.24], EntityLatchedRenderer['unknown'/217, l='MpServer', x=2119.20, y=2.00, z=559.24], ZombieMiner['Zombie Miner'/569814, l='MpServer', x=2136.50, y=15.00, z=612.50], ZombieFarmer['Zombie Farmer'/573160, l='MpServer', x=2116.50, y=53.00, z=540.50], ZombieSoldier['Zombie Soldier'/571628, l='MpServer', x=2093.50, y=75.00, z=496.50], EntityPainting['Painting'/465831, l='MpServer', x=2120.00, y=8.50, z=560.97], EntityPainting['Painting'/465836, l='MpServer', x=2118.50, y=8.50, z=560.97], EntityPainting['Painting'/465835, l='MpServer', x=2117.50, y=8.00, z=560.97], EntityZombie['Zombie'/572640, l='MpServer', x=2065.50, y=75.00, z=511.50], EntityPainting['Painting'/465834, l='MpServer', x=2119.50, y=6.50, z=560.97], ZombieFarmer['Zombie Farmer'/573153, l='MpServer', x=2042.50, y=77.00, z=590.50], EntityPainting['Painting'/465833, l='MpServer', x=2120.50, y=6.50, z=560.97], EntityPainting['Painting'/465832, l='MpServer', x=2118.00, y=6.50, z=560.97], EntityBat['Bat'/571877, l='MpServer', x=2106.80, y=34.06, z=487.07], SkeletonSoldier['Skeleton Soldier'/573432, l='MpServer', x=2123.50, y=46.00, z=557.50], EntityBat['Bat'/572401, l='MpServer', x=2091.39, y=49.03, z=509.75], EntityBat['Bat'/572402, l='MpServer', x=2093.99, y=49.72, z=513.38], EntityBat['Bat'/509948, l='MpServer', x=2118.66, y=5.10, z=528.51], ZombieMiner['Zombie Miner'/573429, l='MpServer', x=2124.50, y=46.00, z=553.50]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/123, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.15.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 680292688 bytes (648 MB) / 1811939328 bytes (1728 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 31 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version               | Source                                          | Signature                                |
	|:------ |:------------------- |:--------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                 | 9.42                  | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                 | 8.0.99.99             | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LCHIJA | forge               | 14.23.5.2847          | forge-1.12.2-14.23.5.2847.jar                   | None                                     |
	| LCHIJA | srm-hooks           | 1.12.2-1.0.0          | minecraft.jar                                   | None                                     |
	| LCHIJA | techguns_core       | 1.12.2-1.0            | minecraft.jar                                   | None                                     |
	| LCHIJA | securitycraft       | v1.8.17               | [1.12.2]+SecurityCraft+v1.8.17.jar              | None                                     |
	| LCHIJA | damageindicatorsmod | 1.0                   | [1.12.2]DamageIndicatorsMod-3.5.1.jar           | None                                     |
	| LCHIJA | gorecore            | 1.12.2-0.4.5          | avatarmod-1.5.17-alpha.jar                      | None                                     |
	| LCHIJA | avatarmod           | 1.5.17-alpha          | avatarmod-1.5.17-alpha.jar                      | None                                     |
	| LCHIJA | blockarmor          | 2.4.11                | BlockArmor-1.12.2-2.4.11.jar                    | None                                     |
	| LCHIJA | cdm                 | 0.4.1                 | device-mod-0.4.1-1.12.2.jar                     | None                                     |
	| LCHIJA | dimdoors            | 3.0.9+287             | DimensionalDoors-3.0.9-287.jar                  | None                                     |
	| LCHIJA | mclib               | 1.0.4                 | mclib-1.0.4-1.12.2.jar                          | None                                     |
	| LCHIJA | emoticons           | 0.4.3                 | emoticons-0.4.3-1.12.2-dist.jar                 | None                                     |
	| LCHIJA | cfm                 | 6.3.1                 | furniture-6.3.1-1.12.2.jar                      | None                                     |
	| LCHIJA | ichunutil           | 7.2.2                 | iChunUtil-1.12.2-7.2.2.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | mts                 | 17.4.2                | Immersive+Vehicles-1.12.2-17.4.2.jar            | None                                     |
	| LCHIJA | jei                 | 4.15.0.291            | jei_1.12.2-4.15.0.291.jar                       | None                                     |
	| LCHIJA | jeresources         | 0.9.2.60              | JustEnoughResources-1.12.2-0.9.2.60.jar         | None                                     |
	| LCHIJA | malisiscore         | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                    | None                                     |
	| LCHIJA | malisisdoors        | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| LCHIJA | mcjtylib_ng         | 3.5.4                 | mcjtylib-1.12-3.5.4.jar                         | None                                     |
	| LCHIJA | pip                 | 7.0.0                 | PiP-1.12.2-7.0.0.jar                            | None                                     |
	| LCHIJA | redstoneflux        | 2.1.1                 | RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
	| LCHIJA | rftools             | 7.73                  | rftools-1.12-7.73.jar                           | None                                     |
	| LCHIJA | secretroomsmod      | 5.6.4                 | secretroomsmod-1.12.2-5.6.4.jar                 | None                                     |
	| LCHIJA | techguns            | 2.0.2.0               | techguns-1.12.2-2.0.2.0_pre3.1.jar              | None                                     |
	| LCHIJA | unuparts            | 3.3.1                 | UNU+Parts+Pack+[MTS]+1.12.2-17.0.0-3.3.1.jar    | None                                     |
	| LCHIJA | unumilitary         | 3.3.1                 | UNU+Military+Pack+[MTS]+1.12.2-17.0.0-3.3.1.jar | None                                     |
	| UD     | mclib_core          | 1.0.4                 | minecraft.jar                                   | None                                     |

	Loaded coremods (and transformers): 
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
McLib core mod (mclib-1.0.4-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-3.5.5' Renderer: 'AMD Radeon Pro 560 OpenGL Engine'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.2
	OpenGL: AMD Radeon Pro 560 OpenGL Engine GL version 2.1 ATI-3.5.5, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz

**Comment by FavouriteDragon** [comment]
Ok, so
-Make sure you've bought minecraft
-Try deleting and reinstalling the mod
-Try deleting your playerdata

**Comment by DancingTillDead** [comment]
> Ok, so
> -Make sure you've bought minecraft
> -Try deleting and reinstalling the mod
> -Try deleting your playerdata

So I've bought Minecraft but I've reinstalled the launcher multiple times, I've already tried reinstalling the mod, but how do you delete your playerdate?

**Comment by 0H4rl3qu1n0** [comment]
> > Ok, so
> > -Make sure you've bought minecraft
> > -Try deleting and reinstalling the mod
> > -Try deleting your playerdata
> 
> So I've bought Minecraft but I've reinstalled the launcher multiple times, I've already tried reinstalling the mod, but how do you delete your playerdate?

You delete your playerdata from the worldfolder. check for your uuid and youll find yours

**Comment by Mahtaran** [comment]
Closed due to inactivity.
