### ISSUE TITLE
Mod Error

### ISSUE THREAD

**Issue by FarPlanets** [ProjectKorra/AvatarMod#143]
The mod works fine when i use it in singleplayer, but then i went to host a server with the same exact version, so I could play with my friend, so once i logged in, i get this error message.

-----------------------------------------------------------------------------------------------------------------

---- Minecraft Crash Report ----
// Why did you do that?

Time: 4/23/20 10:29 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Can't get data for an entity without an UUID
	at com.crowsofwar.avatar.common.data.BendingData.get(BendingData.java:82)
	at com.crowsofwar.avatar.common.bending.water.WaterbendingPerformanceBonus.onWaterbenderUpdate(WaterbendingPerformanceBonus.java:25)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4_WaterbendingPerformanceBonus_onWaterbenderUpdate_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190)
	at net.minecraft.client.entity.EntityOtherPlayerMP.func_70071_h_(EntityOtherPlayerMP.java:63)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.crowsofwar.avatar.common.data.BendingData.get(BendingData.java:82)
	at com.crowsofwar.avatar.common.bending.water.WaterbendingPerformanceBonus.onWaterbenderUpdate(WaterbendingPerformanceBonus.java:25)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4_WaterbendingPerformanceBonus_onWaterbenderUpdate_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190)
	at net.minecraft.client.entity.EntityOtherPlayerMP.func_70071_h_(EntityOtherPlayerMP.java:63)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityOtherPlayerMP)
	Entity ID: 4750
	Entity Name: SamIsAPanMan
	Entity's Exact location: -92.27, 64.00, 56.55
	Entity's Block location: World: (-93,64,56), Chunk: (at 3,4,8 in -6,3; contains blocks -96,0,48 to -81,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['UnPerpendicular'/26130, l='MpServer', x=-92.27, y=64.00, z=56.55], EntityOtherPlayerMP['SamIsAPanMan'/4750, l='MpServer', x=-92.27, y=64.00, z=56.55]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-72,64,-24), Chunk: (at 8,4,8 in -5,-2; contains blocks -80,0,-32 to -65,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 40319 game time, 40319 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 69 total; [EntityPlayerSP['UnPerpendicular'/26130, l='MpServer', x=-92.27, y=64.00, z=56.55], EntityOstrichHorse['Ostrich Horse'/26240, l='MpServer', x=-156.02, y=69.00, z=134.98], EntityHusk['Husk'/26753, l='MpServer', x=-71.50, y=70.00, z=90.50], EntityRabbit['Rabbit'/26242, l='MpServer', x=-108.60, y=63.24, z=126.10], EntityHusk['Husk'/26754, l='MpServer', x=-70.50, y=70.00, z=91.50], EntityRabbit['Rabbit'/26243, l='MpServer', x=-106.73, y=64.00, z=113.52], EntityRabbit['Rabbit'/26244, l='MpServer', x=-107.61, y=63.00, z=134.24], EntityOstrichHorse['Ostrich Horse'/26245, l='MpServer', x=-176.08, y=64.00, z=171.99], EntityOstrichHorse['Ostrich Horse'/26246, l='MpServer', x=-175.12, y=64.00, z=170.85], EntityBat['Bat'/26630, l='MpServer', x=-51.07, y=37.43, z=107.66], EntityCreeper['Creeper'/26377, l='MpServer', x=-57.50, y=26.00, z=54.50], EntityOtherPlayerMP['SamIsAPanMan'/4750, l='MpServer', x=-92.27, y=64.00, z=56.55], EntityOstrichHorse['Ostrich Horse'/26129, l='MpServer', x=-168.60, y=70.12, z=178.58], EntityRabbit['Rabbit'/145, l='MpServer', x=-109.44, y=69.00, z=-3.73], EntityCreeper['Creeper'/26259, l='MpServer', x=-24.50, y=67.00, z=99.50], EntityRabbit['Rabbit'/149, l='MpServer', x=-97.69, y=66.12, z=32.00], EntityRabbit['Rabbit'/150, l='MpServer', x=-90.61, y=73.00, z=13.77], EntityOstrichHorse['Ostrich Horse'/152, l='MpServer', x=-86.04, y=63.00, z=44.90], EntitySkeleton['Skeleton'/26652, l='MpServer', x=-43.50, y=68.00, z=105.50], EntityBat['Bat'/26398, l='MpServer', x=-57.00, y=54.06, z=51.46], EntityCreeper['Creeper'/26529, l='MpServer', x=-69.50, y=27.00, z=2.50], EntityOstrichHorse['Ostrich Horse'/35, l='MpServer', x=-194.50, y=72.00, z=-10.50], EntityOstrichHorse['Ostrich Horse'/36, l='MpServer', x=-197.50, y=72.00, z=-10.50], EntityOstrichHorse['Ostrich Horse'/26151, l='MpServer', x=-206.23, y=71.00, z=40.83], EntityCreeper['Creeper'/26791, l='MpServer', x=-143.50, y=22.00, z=43.19], EntityOstrichHorse['Ostrich Horse'/41, l='MpServer', x=-190.16, y=68.00, z=76.93], EntityOstrichHorse['Ostrich Horse'/42, l='MpServer', x=-185.89, y=65.00, z=84.88], EntityRabbit['Rabbit'/170, l='MpServer', x=-75.58, y=68.00, z=9.13], EntityOstrichHorse['Ostrich Horse'/48, l='MpServer', x=-178.14, y=75.00, z=-12.07], EntityOstrichHorse['Ostrich Horse'/49, l='MpServer', x=-152.04, y=75.00, z=-30.11], EntityOstrichHorse['Ostrich Horse'/50, l='MpServer', x=-181.15, y=77.00, z=35.92], EntityOstrichHorse['Ostrich Horse'/51, l='MpServer', x=-175.60, y=74.00, z=33.50], EntityCreeper['Creeper'/26425, l='MpServer', x=-90.50, y=71.00, z=-6.50], EntityBat['Bat'/26681, l='MpServer', x=-132.11, y=33.00, z=-22.89], EntityRabbit['Rabbit'/186, l='MpServer', x=-29.48, y=69.00, z=-6.60], EntityHusk['Husk'/26428, l='MpServer', x=-25.50, y=69.00, z=-11.50], EntityRabbit['Rabbit'/189, l='MpServer', x=-36.62, y=63.00, z=31.06], EntityRabbit['Rabbit'/190, l='MpServer', x=-37.61, y=67.00, z=38.50], EntitySkeleton['Skeleton'/26430, l='MpServer', x=-30.50, y=69.00, z=-15.50], EntityCreeper['Creeper'/26431, l='MpServer', x=-127.50, y=24.00, z=45.50], EntityCreeper['Creeper'/26176, l='MpServer', x=-124.50, y=22.00, z=78.50], EntityOtherPlayerMP['SamIsAPanMan'/4750, l='MpServer', x=-92.27, y=64.00, z=56.55], EntityRabbit['Rabbit'/26312, l='MpServer', x=-106.52, y=63.00, z=136.43], EntityCreeper['Creeper'/26953, l='MpServer', x=-85.50, y=65.00, z=111.50], EntityBat['Bat'/26570, l='MpServer', x=-104.87, y=36.15, z=-7.94], EntityBat['Bat'/26571, l='MpServer', x=-100.45, y=34.20, z=-6.37], EntityHusk['Husk'/26188, l='MpServer', x=-124.50, y=71.00, z=38.50], EntityRabbit['Rabbit'/205, l='MpServer', x=-19.50, y=64.00, z=62.50], EntitySpider['Spider'/26957, l='MpServer', x=-85.50, y=71.00, z=27.50], EntityRabbit['Rabbit'/206, l='MpServer', x=-20.60, y=64.00, z=62.40], EntitySkeleton['Skeleton'/26704, l='MpServer', x=-146.50, y=33.00, z=45.50], EntityCreeper['Creeper'/26705, l='MpServer', x=-146.50, y=33.00, z=44.50], EntitySpider['Spider'/26966, l='MpServer', x=-129.50, y=72.00, z=-9.50], EntityRabbit['Rabbit'/95, l='MpServer', x=-98.97, y=69.00, z=29.47], EntitySkeleton['Skeleton'/26720, l='MpServer', x=-112.50, y=28.00, z=89.50], EntityRabbit['Rabbit'/97, l='MpServer', x=-94.50, y=71.15, z=-0.20], EntityCreeper['Creeper'/26595, l='MpServer', x=-97.50, y=73.00, z=-15.50], EntitySpider['Spider'/26474, l='MpServer', x=-12.50, y=65.00, z=64.50], EntityRabbit['Rabbit'/113, l='MpServer', x=-104.61, y=69.00, z=-9.05], EntityRabbit['Rabbit'/114, l='MpServer', x=-97.87, y=69.00, z=-5.65], EntityBat['Bat'/26354, l='MpServer', x=-94.50, y=25.32, z=-17.48], EntityRabbit['Rabbit'/118, l='MpServer', x=-91.78, y=74.00, z=18.52], EntityOstrichHorse['Ostrich Horse'/26233, l='MpServer', x=-194.95, y=63.00, z=126.67], EntityOstrichHorse['Ostrich Horse'/26234, l='MpServer', x=-183.91, y=69.00, z=135.66], EntityOstrichHorse['Ostrich Horse'/26235, l='MpServer', x=-191.85, y=64.00, z=130.52], EntityOstrichHorse['Ostrich Horse'/26236, l='MpServer', x=-188.35, y=66.00, z=138.97], EntityOstrichHorse['Ostrich Horse'/26237, l='MpServer', x=-198.26, y=64.00, z=140.61], EntityOstrichHorse['Ostrich Horse'/26238, l='MpServer', x=-200.97, y=64.00, z=133.97], EntityOstrichHorse['Ostrich Horse'/26239, l='MpServer', x=-154.01, y=70.00, z=142.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 257503960 bytes (245 MB) / 536870912 bytes (512 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature |
	|:------ |:--------- |:------------ |:----------------------------- |:--------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None      |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None      |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | forge     | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | gorecore  | 1.12.2-0.4.5 | avatarmod-1.5.17-alpha.jar    | None      |
	| LCHIJA | avatarmod | 1.5.17-alpha | avatarmod-1.5.17-alpha.jar    | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4252' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4252, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
--------------------------------------------------------------------------------------------------------------

Please help whenever you can, thanks!

**Comment by FavouriteDragon** [comment]
Have you both bought minecraft? Is the server in online mode?

**Comment by Toakan** [comment]
@FavouriteDragon This is nothing to do with owning the game. This is a bug which occurs when accessing certain mod items; the crash is repeatable with different mods'.

For instance, if you use https://www.curseforge.com/minecraft/mc-mods/constructs-armory and try to access the Armour Station without any equipment in your player inventory, but bending skills unlocked, the game will crash.

[crash-2020-06-17_22.49.10-client.txt](https://github.com/ProjectKorra/AvatarMod/files/4795273/crash-2020-06-17_22.49.10-client.txt)

**Comment by Mahtaran** [comment]
It would be a little more helpful if you could just answer the question directly: do you use cracked/illegal accounts or is your server running in offline mode?

**Comment by Toakan** [comment]
Take the hints.
- Do you use cracked/illegal accounts: No
- Is your server running in offline mode: No

**Comment by Mahtaran** [comment]
What is weird is that I do not see any other mods in your crash report.

**Comment by Toakan** [comment]
Lines 3 - 10 of the crash report.
```
WARNING: coremods are present:
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.12.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

```

If you are having issues debugging the problem, say that and ask for more information.

**Comment by FavouriteDragon** [comment]
Ok this is fixed in the next update, this is to do with fake player shenanigans and stupid crap

**Comment by zoobeeplant101-web** [comment]
Hi, I just got the same issue trying to play with my friend on 1.12.2 how did you fix it?
