### ISSUE TITLE
Adding bending glitch

### ISSUE THREAD

**Issue by HugoDaBozza1146** [ProjectKorra/AvatarMod#144]
whenever i would like to use the add bending command to get all or any specific type of bending a message pops up saying that an unknown error has occurred try using the /help option to resolve and the i do so but the it just say another error has occurred and i have tried taking out all the other mods i have been using but it still doesn't work.......ant suggestions???????would really appreciate it.

**Comment by FavouriteDragon** [comment]
Have you bought minecraft? Did you install your mods correctly? if you're on a server, install the mod on the server.
