### ISSUE TITLE
Slipstream causes issues walking on paths

### ISSUE THREAD

**Issue by SangurianSoul** [ProjectKorra/AvatarMod#145]
Slipstream level 1 and 2 do not seem to cause any issues that ive noticed after hours of play, until i level it again.

Upon leveling my Slipstream to level 3, and upon first use when i get into a game, from here on out i cannot walk up stairs if there is a path right before them.

if i reconnect, i can walk up stairs just fine. until i use my slipstream. the ability works as intended while it is in use, but once it wears off, i seem more grounded than usual.

Its like i cant walk up that extra 1/16 of a block that adding a path creates without my bending.

Upon further investigation, Divine Breeze level up possess the same issue. However, even more odd, Run Like the Wind causes another issue while it is active, in that, you cant walk from a path to another block, even if they are level. you are completely stopped in your tracks by that 1/16 while RLtW is active. while not active, you still have the issue of not being able to go from path to stairs.

**Comment by FavouriteDragon** [comment]
Ok after reviewing the test builds, everything works fine for me except RLtW. However, I'm just gonna claim this is intentional since you can run on air with that upgrade, so it's a tradeoff that's worth it.
