### ISSUE TITLE
I can't open the skills menu

### ISSUE THREAD

**Issue by rosetao** [ProjectKorra/AvatarMod#147]
I can't open the skills menu, i tried to change keys, switch accounts and nothing worked, my frined and i are playing in the same server and he can open it.

**Comment by lukenator115** [comment]
This is like the LAN server issue, where mod won't work for people joining - if you right-click a scroll you'll get the menu, but if it's the same issue nothing will unlock. Sadly I don't have a fix

**Comment by FavouriteDragon** [comment]
Ok make sure the server is in online mode and that you've both bought mc
