### ISSUE TITLE
Mod broken

### ISSUE THREAD

**Issue by XxsjrapsxX** [ProjectKorra/AvatarMod#149]
This mod seems very broken at the moment, i cant get most of the bendings to work, i cant unlock them or use them, especially with air, and my chi bar isnt showing up, would reverting to a previous version be better as of right now?

**Comment by XxsjrapsxX** [comment]
to be specific, its mainly the server problems. When trying to run a server with this mod it seems to not function very well

**Comment by FavouriteDragon** [comment]
Make sure the server has online mode enabled.
