### ISSUE TITLE
Sync config between client/server

### ISSUE THREAD

**Issue by CrowsOfWar** [ProjectKorra/AvatarMod#15]
When a client joins a server, a packet to client should be sent which contains the config values. The client will then use those config values until (s)he leaves the server.

**Comment by FavouriteDragon** [comment]
@CrowsOfWar is this done?

**Comment by CrowsOfWar** [comment]
@FavouriteDragon nope, let me know if you guys are thinking about it ever.

**Comment by FavouriteDragon** [comment]
ah this is why keybinds aren't saved
@Mahtaran will do this when he gets back

**Comment by FavouriteDragon** [comment]
@CrowsOfWar Ok I wanna do this now!
