### ISSUE TITLE
Bending abilities won't activate

### ISSUE THREAD

**Issue by Robomarti** [ProjectKorra/AvatarMod#162]
Basically once I have pressed air jump hotkey I get the indicator that it would activate once I jump, but no matter how many times I jump it won't activate. Water skate and fire jump also just "stack" on the indicator part under my cursor. If I try to press them again, I still cant jump and the icons stay under my cursor. Also waterskating won't stop if I don't press shift while on water, it keeps running even when on shore, and I cant jump off the water level so I'm just aimlessly running towards few blocks that are 1 level upper than the water level
Screenshot of the bending icons stacking under my cursor (I didn't activate them all at the same time, first my air jump got glitched, then my fire jump and then it left me with waterskating as my last mobility bending, and now that too has glitched so I feel really clumsy compared to what I was earlier) :
[2020-06-25_12 50 26](https://user-images.githubusercontent.com/42907675/85697796-c8720080-b6e2-11ea-9a5e-c48a672ace53.png)

**Comment by SnowyPotat** [comment]
Try checking your controls to see if your spacebar is being connected to anything besides your character.
Try checking this website to find other things.
 https://projectkorra.fandom.com/wiki/Av2:AirJump

**Comment by Mahtaran** [comment]
Closed due to inactivity. Reopen if the issue is still happening even with `SnowyPotat`'s advice.
