### ISSUE TITLE
Cant bend more than one element

### ISSUE THREAD

**Issue by Gogoasha** [ProjectKorra/AvatarMod#169]
the command /avatar bending add @p and so on, doesn't work for me, all i get is:the value air for the argument bending is not an option. and that's it. also if i add an ability i cant change that menu, when you press K, the earth stays. basically i dont know how to change between elements and how to use more than one.

**Comment by TFORTNT** [comment]
you are probably typing something along the lines of /avatar bending add (username) air.  At the end however, you need to add the word bending.  

Ex of mine:  /avatar bending add TFORTNT airbending

**Comment by Gogoasha** [comment]
i would like to say that i never wrote "airbending", just "air" and it never worked, i'll open the game and try it rn. and also, how to change the element that appears in that circle ? yk what i mean, that circle that shows you your skills and stuff

**Comment by TFORTNT** [comment]
it's not suppose to work if you just type "air", you need to add the "bending" part after making it airbending.

For the cycling elements, the default buttons are z and v, but I would change it to something to feel more comfortable with in setttings then controls

**Comment by Gogoasha** [comment]
well now that's something i knew and i thought that i was wrong. i'm spamming Z and V and nothing happens, it just stays on airbending

**Comment by Gogoasha** [comment]
nevermind i didn't have to open that circle, i had to press Z and V with clean screen. basically you just tought me how to use this mod in less than 10 minutes, i've been searching for tutorials for 3 days so far, thanks man, makes a lot
