### ISSUE TITLE
We can´t play with an specific player.

### ISSUE THREAD

**Issue by Tarnia919** [ProjectKorra/AvatarMod#178]
At first, we, two friends and I, thought this issue had something to do with our friend´s computer - I´ll call her Friend 2 - but the crash report showed that the Avatar mod is the thing that is causing the issue. Friend 1 and I can play with no problems, the mod and server work perfectly, but the second Friend 2 joins our server, we are both kicked out of it. And if she is playing, the server won´t let us in. We have the same mods, the same Forge, the same Java version, etc. We have no idea what is actually causing the issue, besides that it has something to do with the Avatar mod. We could fix the problem just by not playing with the mod, but the reason we wanted to play together in the first place was so we could battle together, have Agni Kais and stuff.

Here is the most recent crash report.

[crash-2020-08-04_17.12.34-client.txt](https://github.com/ProjectKorra/AvatarMod/files/5023113/crash-2020-08-04_17.12.34-client.txt)

**Comment by FavouriteDragon** [comment]
Make sure the server is in online mode, and that you have both bought mc.
As for Agni Kais- they're not *quite* fully realised in the public release, but the next update will basically let you do them in terms of dynamic collision and visuals.

**Comment by Mahtaran** [comment]
Definitely an issue with the server not being in online mode.
