### ISSUE TITLE
Can I spawn benders?

### ISSUE THREAD

**Issue by Tarnia919** [ProjectKorra/AvatarMod#181]
I have been playing for a short time, looking at all the items the mod has, and I haven´t seen a way to spawn benders like you could spawn villagers or animals. I want to make a world and build villages there, and I´d like to place benders in them, but I don´t know if  it´s possible.

**Comment by Mahtaran** [comment]
You should be able to spawn them using the `/summon` command. Tab-completion should help you figuring out their identifiers.
