### ISSUE TITLE
Summon command doesn´t work for benders.

### ISSUE THREAD

**Issue by Tarnia919** [ProjectKorra/AvatarMod#182]
When I try to summon a vanilla mob, like a wolf, everything works. But I can´t spawn benders with the command, only with the eggs from creative mod, and that would be perfect if water and earthbenders were there; instead, there are only fire and airbenders. I´ve tried writing "/summon waterbender" and "/summon Waterbender" but it always says "Unable to summon object". Am I doing something wrong?

**Comment by Mahtaran** [comment]
Yes. You have to add the mod identifier. Use tab-completion, it makes your life a lot easier. Also note that there are no earthbenders in the mod yet.

**Comment by Tarnia919** [comment]
Now it worked! Thank you!
