### ISSUE TITLE
Jumping Skills not working at all?

### ISSUE THREAD

**Issue by HyperMan19680** [ProjectKorra/AvatarMod#188]
So I learned both the Air Jump and the Fire Glide skills in the newest alpha for 1.12.2, and I noticed they aren't working at all. Is there something I'm doing wrong, or is it intended for it to not activate each time?

**Comment by FavouriteDragon** [comment]
Uh- you just use the ability then press your jump key.

**Comment by FavouriteDragon** [comment]
Are they on cooldown or something?

**Comment by FavouriteDragon** [comment]
No new info, so I'm closing
