### ISSUE TITLE
[Suggestion] Earth Wall Suggestion

### ISSUE THREAD

**Issue by LatentDesire** [ProjectKorra/AvatarMod#19]
After raising a wall, an earth bender could smack blocks in the opposite direction. I remember Witchery had a somewhat similar ability with one of it's infusions. Possibly requiring an empty hand.

**Comment by CrowsOfWar** [comment]
So kind of like kicking off part of the wall at the enemy?

**Comment by LatentDesire** [comment]
Pretty much, yeah. I thought I remembered seeing it in the series, and sure enough. 

https://youtu.be/CmEo-U9gAn4

Around the 1:12 mark. I think I've seen Toph to something similar too.

**Comment by LatentDesire** [comment]
Yeah. She does a similar technique towards the end of this video. 

https://youtu.be/xtBbtAAEdhY

**Comment by CrowsOfWar** [comment]
Yeah definitely is a good idea. I'll see if I can implement this.

**Comment by LatentDesire** [comment]
Cool.

**Comment by FavouriteDragon** [comment]
This is done as part of a path.
