### ISSUE TITLE
Incapability with auto clickers from any mod

### ISSUE THREAD

**Issue by kirjorjos** [ProjectKorra/AvatarMod#198]
When attempting to simulate the action of using an item, my game crashes.  This specific log is from the Extra Utilities 2 on the Astral Sorcery Light well.
[crash-2020-12-06_22.14.28-server.txt](https://github.com/ProjectKorra/AvatarMod/files/5655633/crash-2020-12-06_22.14.28-server.txt)
This is my first GitHub issue so sorry if I'm missing any information that I should put in here.

**Comment by FavouriteDragon** [comment]
Fixed in 1.6.0 and its alphas
