### ISSUE TITLE
Long list of polish

### ISSUE THREAD

**Issue by CrowsOfWar** [ProjectKorra/AvatarMod#2]
Here is a list of things which must be polished.
More can be found in Eclipse's Tasks view. (TODO comments)
This will probably remain open, you can comment to request new polishing features.
Note: This is for small patches that make the mod better and more immersive. It's not for large or complicated bugs.
- Sounds for fire/water (Where to get them?)
- Fix backwards movement of water arc
- Fire arc thrown into water creates fire for a moment. (then the water engulfs the fire block)
  - Results are a bit random- try it a few times.
- Vanilla water texture for water arc

**Comment by CrowsOfWar** [comment]
Removed a few which were done earlier.

**Comment by CrowsOfWar** [comment]
Fixed:

- Fix floating block placement using items
- Fix Left-click and right-click controls still firing even if in the Pause menu (try lighting a fire arc then escape, left-click, escape)

**Comment by FavouriteDragon** [comment]
Hmm this is all fixed except for water arc using the vanilla water texture

**Comment by FavouriteDragon** [comment]
Done everything!
