### ISSUE TITLE
[Suggestion] Snow as water source/misc water sources

### ISSUE THREAD

**Issue by LatentDesire** [ProjectKorra/AvatarMod#20]
Just thought I'd put this up as a suggestion that snow be counted as a source of water for bending. With the snow layers that can come from rain on mountain tops or snow golems counted as one charge for the purposes of throwing, and blocks of snow counted as source blocks. If it can also be used for the wave ability (and the water running), that would also be useful.

Also I've heard of the biome tag wet. (And maybe just medium humidity) Perhaps if not targeting a source block in this kind of biome and using the ability that lets you pick up water blocks, it could draw moisture from the air. Maybe with an increase in chi used depending on how wet/dry the biome is. (Trying this in the water would make you S.O.L.) Perhaps this can be locked at the highest level of this skill. 

An intermediate upgrade can be drawing water blocks from a 3 x 3 of grass or a leaf block. (My guess being there is more water in a block of leaves than in a single grass block.) Again at a slight increase in chi used, but not as much as trying to get water from the moisture in the air.

**Comment by LatentDesire** [comment]
Oh, and the grass can turn to dead grass which eventually becomes a regular dirt block. (And can be fixed over time by vanilla mechanics) The leaves used in this way just break.

**Comment by LatentDesire** [comment]
Was watching this ( https://youtu.be/Z_91fGmhECE ), and it might be a bit OP, but infinite ammo for water bending when it's raining. 
(Though considering how much earth and air there is, maybe not. And firebenders can make their own fire. Lol) 

(Other side note: No air bending in the vacuum of space for mods that add such. Ex. Advanced Rocketry, and Galiticraft if it's been updated.)



(Which made me remember, water bending should be stronger/weaker depending on the moon phase. Strongest during a full moon and vice versa for a new moon.)

**Comment by CrowsOfWar** [comment]
Yeah, these are good ideas. The reason I didn't allow waterbenders to use leaves/grass for water is because I'm saving that for plantbending, which you would have to learn (instead of already knowing it). But this is good info for plantbending.

Also, will add the raining idea, thanks!

**Comment by LatentDesire** [comment]
Ah, that sub bending style. That's more working with the plant I think. I'm referring to as how it was used when Katara was facing the blood bender. It's swift, but violent, and kills the plants since it's literally tearing out the water. When I think of plant bending, I think of bending the water in the plant, to move the plant (like vines and such.) This is similar to how Metalbending is described (as bending the earthy impurities in the metal, to get it to do what you want).

**Comment by LatentDesire** [comment]
Come to think of it, maybe this is how that lost airbending art of flying works (like that guy in Korra). By bending the air inside yourself? (Did I just figure it out?)

**Comment by FavouriteDragon** [comment]
Plants and snow are now bendable. The lists are configurable; gonna be working out the glitches and bugs over the next months,
