### ISSUE TITLE
1.6 Alpha Crash with Chocolate Quest Repoured

### ISSUE THREAD

**Issue by voidswrath** [ProjectKorra/AvatarMod#200]
This crash happens on client load up.

Forge: 2854
Avatar Version: avatarmod-1.6.0-alpha.5
Chocolate Quest Repoured version: Chocolate_Quest_Repoured-1.12.2-2.1.3B

Crash Report: https://pastebin.com/XmBhYebB

**Comment by FavouriteDragon** [comment]
That should be fixed in the next update!
