### ISSUE TITLE
Mod for server

### ISSUE THREAD

**Issue by PandaR3D** [ProjectKorra/AvatarMod#215]
I tried to create a server with the mod but it wouldn't let me use the bends and they didn't even appear at the bottom right

**Comment by litcritter** [comment]
I'm having the same issue. I created a server using forge-1.12.2-14.23.5.2838 and avatarmod-1.5.17-alpha and am running the same as my client. As client, I can create a single player world and unlock bending with no problem, but when I join the server (hosted on my machine, accessible by my kids via direct connection over LAN), we cannot unlock bending with scrolls (we click the box and nothing happens) or by command (I get an unknown command error).
![Avatar mod Screenshot 2021-02-21 113130](https://user-images.githubusercontent.com/79415789/108633163-61a31380-7438-11eb-9a50-43a357a9cf5c.png)

I've attached the latest.log but I'm not seeing anything in there that's much help. I'm at a loss. Anyone solved this and can share their wisdom?

`[11:24:16] [Server thread/INFO]: Loading properties`
`[11:24:16] [Server console handler/ERROR]: Exception handling console input`
`java.io.IOException: The handle is invalid`
`	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_271]`
`	at java.io.FileInputStream.read(Unknown Source) ~[?:1.8.0_271]`
`	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.8.0_271]`
`	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.8.0_271]`
`	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[?:1.8.0_271]`
`	at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:1.8.0_271]`
`	at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:1.8.0_271]`
`	at java.io.InputStreamReader.read(Unknown Source) ~[?:1.8.0_271]`
`	at java.io.BufferedReader.fill(Unknown Source) ~[?:1.8.0_271]`
`	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_271]`
`	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.8.0_271]`
`	at nz$2.run(SourceFile:100) [minecraft_server.1.12.2.jar:?]`
`[11:24:16] [Server thread/INFO]: Default game type: SURVIVAL`
`[11:24:16] [Server thread/INFO]: Generating keypair`
`[11:24:16] [Server thread/INFO]: Starting Minecraft server on *:25565`
`[11:24:16] [Server thread/INFO]: Using default channel type`
`[11:24:16] [Server thread/INFO]: Preparing level "world"`
`[11:24:16] [Server thread/INFO]: Loaded 488 advancements`
`[11:24:16] [Server thread/INFO]: Preparing start region for level 0`
`[11:24:16] [Server thread/WARN]: Skipping Piece with id waystones:village_waystone`
`[11:24:17] [Server thread/INFO]: Done (1.053s)! For help, type "help" or "?"`
`[11:26:22] [Server thread/INFO]: Opped litcritter`
`[11:28:31] [User Authenticator #1/INFO]: UUID of player Litcritter is f0c5cdf7-47b1-4871-9a4f-ddca8c58aa22`
`[11:28:31] [Server thread/INFO]: Litcritter[/192.168.1.31:51010] logged in with entity id 258 at (101.54364029835929, 74.53292827534491, 258.4364217697863)`
`[11:28:31] [Server thread/INFO]: Litcritter joined the game`
`[11:28:59] [Server thread/INFO]: [Litcritter: Set the time to 1000]`
`[11:29:34] [Server thread/INFO]: [Litcritter: Set own game mode to Survival Mode]`
`[11:29:52] [Server thread/INFO]: [Litcritter: Set own game mode to Creative Mode]`
`[11:33:14] [Server thread/INFO]: [Litcritter: Set own game mode to Survival Mode]`
`[11:33:30] [Server thread/INFO]: [Litcritter: Set own game mode to Creative Mode]`
`[11:33:32] [Server thread/INFO]: Litcritter lost connection: Disconnected`
`[11:33:32] [Server thread/INFO]: Litcritter left the game`
`[11:33:43] [Server thread/INFO]: Stopping server`
`[11:33:43] [Server thread/INFO]: Saving players`
`[11:33:43] [Server thread/INFO]: Saving worlds`
`[11:33:43] [Server thread/INFO]: Saving chunks for level 'world'/overworld`
`[11:33:43] [Server thread/INFO]: Saving chunks for level 'world'/the_nether`
`[11:33:43] [Server thread/INFO]: Saving chunks for level 'world'/the_end`
`[11:33:43] [Server Shutdown Thread/INFO]: Stopping server`
`[11:33:43] [Server Shutdown Thread/INFO]: Saving players`

**Comment by FavouriteDragon** [comment]
1) Make sure everyone on your server has bought Minecraft. 2) Enable online mode in your server.properties. 3) Try deleting your playerdata, uuidcache, and other userdata/uuid files.

**Comment by mahtaran** [comment]
Closed due to having had no update in a long time.
