### ISSUE TITLE
No possibility to add a second bending to the first bending

### ISSUE THREAD

**Issue by michel8988** [ProjectKorra/AvatarMod#216]
Once you chose for one element, the gui / interface does not make it possible to add a second bending. (Annoying when you created a server without cheats.)

**Comment by hdkd4** [comment]
Sneaky tip! (in a singleplayer world) You can open your game to the public networks using the open to LAN button and turn on cheats from there! It won't be permanent, but it's useful if you created a world but forgot to turn on cheats or just don't want people using cheats on a public world. If you mean open, like, a realms server, I don't know, I don't have any experience with those. anyways, I hope this helps!

**Comment by michel8988** [comment]
> Sneaky tip! (in a singleplayer world) You can open your game to the public networks using the open to LAN button and turn on cheats from there! It won't be permanent, but it's useful if you created a world but forgot to turn on cheats or just don't want people using cheats on a public world. If you mean open, like, a realms server, I don't know, I don't have any experience with those. anyways, I hope this helps!

**Comment by michel8988** [comment]
Thank you!
