### ISSUE TITLE
Can't Add Bending

### ISSUE THREAD

**Issue by 1Toatser** [ProjectKorra/AvatarMod#220]
So I do the command /avatar bending add (Id) airbending. It says I am an airbender but abilities don't come up.

**Comment by hdkd4** [comment]
What exactly do you mean by that? Does the window pop up but there isn't any abilities? Or does the window not pop up at all?

**Comment by 1Toatser** [comment]
So no window pops up and no fire symbol is added next to other bending.

**Comment by hdkd4** [comment]
I don't work here, but I would still like to help. Are you using the mod version 1.6.0 or 1.5.17? If you're not using either of them, I would suggest updating the mod to 1.5.17, due to there being no waterbending in 1.6.0 as of yet. There may also be a problem with another mod in your mods folder.

**Comment by mahtaran** [comment]
Closed due to having had no update in a long time. Thanks for delivering assistance @hdkd4
