### ISSUE TITLE
the air bending scroll is wrong 

### ISSUE THREAD

**Issue by ballsofheaven** [ProjectKorra/AvatarMod#221]
cloudburst takes a level 3 scroll instead of a level 2 

https://user-images.githubusercontent.com/61277043/108513778-54184d00-72c3-11eb-913f-e4ba4b769a95.mp4

**Comment by ballsofheaven** [comment]
i tested with a level 3 scroll later and it worked

**Comment by ballsofheaven** [comment]
1.6.0 ALPHA 14

**Comment by FavouriteDragon** [comment]
You need a tier 3 scroll to unlock it.

**Comment by FavouriteDragon** [comment]
Check the description.
