### ISSUE TITLE
Disconnect on join

### ISSUE THREAD

**Issue by NikeSchuh** [ProjectKorra/AvatarMod#223]
When I / My Friends join my Server they get kicked and the server freezes with the following exception spamming into
the console.
Version: avatarmod-1.6.0-alpha.14
Forge: 14.23.5.2854
https://pastebin.com/Q1J4RgpS

**Comment by FavouriteDragon** [comment]
Thanks! Pretty sure I've fixed that, but I'll see.

**Comment by FavouriteDragon** [comment]
This should be fixed in the next update
