### ISSUE TITLE
[Suggestion] UI Enhancements

### ISSUE THREAD

**Issue by NikeSchuh** [ProjectKorra/AvatarMod#224]
Maybe add an option to disable the avatar mod ui completely. If the mod is in an modpack and some people dont wanna play it
they always have the avatar ui.

**Comment by wolfkidsounds** [comment]
@NikeSchuh 

The UI is not enabled when someone does not have bending abilities. (When someone has not used a scroll and has not attached a "bendingskill")

**Comment by FavouriteDragon** [comment]
Already exists. Check your client config in 1.6.0.
