### ISSUE TITLE
LAVA makes the game weird especially the master glider 

### ISSUE THREAD

**Issue by ballsofheaven** [ProjectKorra/AvatarMod#225]
ive cataloged all the issues ive had with the lava "bug" ive found . it made very difficult traveling in the nether 

https://www.youtube.com/channel/UCEUMgI8syI0PYaatmd8Rr8A****
i leave my youtube page with all the videos

if you need aditional information just ask

**Comment by FavouriteDragon** [comment]
Uh it's a bad implementation of hot air (lava = speed).

**Comment by mahtaran** [comment]
Closed due to having had no update in a long time. If this is still a current issue, reopen or file a new issue.
