### ISSUE TITLE
Move Block Ability not working. 

### ISSUE THREAD

**Issue by PurelyAliyah** [ProjectKorra/AvatarMod#227]
It's been noticed on my server by a couple of earth benders that "when we click on the move but nothing seems to happen. But it works just fine will testing it in a single player world, It still uses chi but no blocks break. It's the only move that doesn't seem to work"

Any help would be wonderful.

**Comment by Sarous** [comment]
This commonly happens when attempting to use Earth Control while still under cooldown. The block is removed from the world, but the cooldown is preventing it from being "controllable". Would be nice if the cooldown check was performed before the block's removal from the world.

**Comment by FavouriteDragon** [comment]
Ngl thought I fixed that but oh well. Mod version?

**Comment by Sarous** [comment]
I'm using Alpha-14

**Comment by FavouriteDragon** [comment]
Fixed
