### ISSUE TITLE
Biomes O' Plenty not compatible with Earth Bending

### ISSUE THREAD

**Issue by EmeryGamingZ** [ProjectKorra/AvatarMod#230]
For instance, you can't pick up blocks with the "Earth Control" ability from other mods, or other abilities that affect the ground.

**Comment by Sarous** [comment]
This is not so much an "incompatibility" as the blocks have not been addedin the config's database (config/avatar/skills.yml). Its easy to add them manually: F3+H while in-game will allow you to see the block ID names.

**Comment by FavouriteDragon** [comment]
Use 1.6.0. There's an option for a lazy config, or manually add them as described above.
