### ISSUE TITLE
Air Glider [Closed]

### ISSUE THREAD

**Issue by Sarous** [ProjectKorra/AvatarMod#231]
This might be my own ignorance, but I do not see a way to achieve sustained flight, even as an Airbender. No matter what i do, I am unable in increase altitude in-flight.

avatarmod-1.6.0-alpha.14

**Comment by chase8201** [comment]
Exactly what I had wondered, one of the builds that I had used a while back had a feature of where you were able to glide throughout the air with ease but I wondered what had happened to it after?

**Comment by Sarous** [comment]
Somehow I got the Master Glider to effectively function as a self propelled object, with steering that only worked in 3rd player view like a Elytra. I have sofar been unable to repeat the incident.

**Comment by FavouriteDragon** [comment]
Memory drain is probably a combination of java + me not properly managing modified abilities when using a glider.
