### ISSUE TITLE
Firebending

### ISSUE THREAD

**Issue by Sarous** [ProjectKorra/AvatarMod#234]
Issue 1) Fire Shot will occasionally lock into an infinite "This ability is on Cooldown" which never ends. Activating Creative while in this infinite cycle allows it to be used (by simply ignoring the cooldown while in creative) but this does not fix the problem upon returning to Survival. Original cause of the lockdown is yet unknown.

**Comment by FavouriteDragon** [comment]
Ah really? Frick

**Comment by FavouriteDragon** [comment]
Should be fixed
