### ISSUE TITLE
Hunger Drain

### ISSUE THREAD

**Issue by Sarous** [ProjectKorra/AvatarMod#235]
Using bending moves reduces hunger at a rate that is insatiable, and there is currently no way, or config options, to reduce or remove this penalty.

**Comment by FavouriteDragon** [comment]
Uh it doesn't reduce it that fast? Just don't sprint while using it lmao. And there is a way. Check .config/avatar/abilities, change exhaustion. Or, overall buff stuff with their powerLevel in your stats config.

**Comment by FavouriteDragon** [comment]
I'll nerf inhibitors tho
