### ISSUE TITLE
Mob lag

### ISSUE THREAD

**Issue by Sarous** [ProjectKorra/AvatarMod#236]
Occasionally, following various bending moves, I have noticed mobs moving abnormally quickly- both their animation and absolute walking speed. I've reasoned that it has to be related to server clock speed lagging then accelerating to catch up. This will occur both during active combat with mobs, and within minutes following bending, even when no bending is currently being performed.

[Alpha-14]

**Comment by FavouriteDragon** [comment]
....Yeah that's probably on me, I'll see what I can do.

**Comment by FavouriteDragon** [comment]
....The log is pain. Gonna test something real quick and seems if it persists
