### ISSUE TITLE
Avatar/Clumps mod compatibility

### ISSUE THREAD

**Issue by Sarous** [ProjectKorra/AvatarMod#237]
Clumps is a mod to consolidate xp orbs into a singular orb. With Avatar added, clumps no longer seems to function, resulting in multiple xp orbs (usually two).

Not exactly a high priority, but, its a bug!

[Alpha-14]

**Comment by FavouriteDragon** [comment]
What in le fock
Logs? Thank you!

**Comment by mahtaran** [comment]
Closed due to having had no update on the logs request in a long time.
