### ISSUE TITLE
Earth Control (another new bug)

### ISSUE THREAD

**Issue by Sarous** [ProjectKorra/AvatarMod#240]
Alpha-14
Earth Control Rank1

Rare bug where right-clicked blocks simply disappear, no cooldown is triggered. It is possible to chain-use the ability to clear great areas, one block at a time as fast as you can click it. Once this bug occurs, the effect can be duplicated infinitely, however I have not yet figured out how to initiate the bug due to its rarity.

Edit:
Started just playing with the bug, since it was already triggered. This appears to be closely related to the Cooldown bug of the same ability:
Trying to place a controlled block in this state has no effect- EXCEPT, when clicking on the space of a block which disappeared because of this block- which replaces per the movecooldown bug. Replacing EVERY block which was removed seems to clear this bug.
Cooldown is entirely failing to trigger on this ability by any means, reason unknown (possibly mod interaction, as I'd just added another mod). Once cleared, this bug is re-triggering each time I try to use it.

**Comment by FavouriteDragon** [comment]
Fixed
