### ISSUE TITLE
Enable/Disable Config Mob Spawns

### ISSUE THREAD

**Issue by wolfkidsounds** [ProjectKorra/AvatarMod#241]
In the latest release version the "maximum benders" option does not turn off the spawning of benders. 

Also I would like to be able to turn spawning of your entities (*skybison, firebender, airbender*) on/off. 
(also for compat reasons).

**Comment by FavouriteDragon** [comment]
Yeah uh 1.6.0, right? Or 1.5.17?

**Comment by wolfkidsounds** [comment]
This is concerning 1.5.17 - But i'll download your latest alpha and test again?:)

**Comment by mahtaran** [comment]
Closed due to having had no updates in four months. If the issue persists, reopen it again, or file a new issue.
