### ISSUE TITLE
Compat for Dimension Changing Mods (Galacticraft)

### ISSUE THREAD

**Issue by wolfkidsounds** [ProjectKorra/AvatarMod#242]
Some Dimension changes/modded dimensions disable or break the bending abilities. (For example the mining ability).
The real problem arrives when you play on a server, since this problem affects everyone (not only the played changing the Dimension).

---

Idea to quickly solve this would be to have a config option to input dimension IDs where the avatarmod "disables" its features for compat reasons. (Also usefull if you want to have the opposite a "bending dimensions" maybe usefull for modpacks).

**Comment by FavouriteDragon** [comment]
Huh
Can I get more info/ a log?
