### ISSUE TITLE
I modified the jar for a Modpack?

### ISSUE THREAD

**Issue by wolfkidsounds** [ProjectKorra/AvatarMod#244]
I have modified the jar file (removed HumanBenderSpawn classes). 

**I would like to use this modified version for a modpack (that is hosted on curseforge). Am I allowed to do that?**

CurseForge also would not support uploading custom *jar* files (except they are on their whitelist). Would it be okay if this version is re-uploaded as experimental *new* project (from my side).

*Or maybe you can add as "additional file" on your curseforge page?*

---

**Reasoning for the modification:**

The AvatarMod sometimes does spawn its entities nearly uncontrollably.
I've had a hard time hooking into it with spawn-changing mods (for example InControl). 
The mod just plainly ignores all set rules (skybison at least reacts to removing potential spawning). However Airbender and Firebender still Spawn either way.

**The real problem:**

We had some issues where tick time was unusually high. So we started Investigation running the spark profiler and the laggoggles profiler. Turns out "HumanBenderSpawner" takes nearly 30% of all tick time, sometimes even more looking for spawn chunks and villages. (We disabled village Generation).

I have tried to make my own mod first but since the class will get asm transformed I don't have enough knowledge to kind off cancel the events before they even get transformed. I looked at the code and the most simple solution for me, was to just delete the classes inside the jar...

We also would simply disable scroll trading and let them drop only by bounties and Mob Kills.

**Comment by FavouriteDragon** [comment]
Ok so
1) You are in fact allowed to use a modified version as long as you state what you have changed (under the license), so no worries with legality there.
2) I've actually changed spawning and fixed that in 1.6.0+. As for sky bison spawning, I think there's a config option. If not, tell me what you want customisable and I'll add it.
3) I can make a config option for mob trading too.
Essentially, I've fixed that in newer versions, but they're alphas (cause no water + ice)

**Comment by wolfkidsounds** [comment]
> Ok so
> 
> 1. You are in fact allowed to use a modified version as long as you state what you have changed (under the license), so no worries with legality there.
> 2. I've actually changed spawning and fixed that in 1.6.0+. As for sky bison spawning, I think there's a config option. If not, tell me what you want customisable and I'll add it.
> 3. I can make a config option for mob trading too.
>    Essentially, I've fixed that in newer versions, but they're alphas (cause no water + ice)

Thank you very much. - The only problem is, that we use the version before 1.6 alpha because of some other things, broken abilities and such.

In essence I literaly deleted the "HumanBenderSpawn" classes to remove the (really high amount of ticks used).

In fact, there is a config for mob trading, but setting values to 0 does not work.


The config situation is probabl related to #241 ... -> I would in general like to be able to turn on/off all of the mobs, but in essence before they even check if they can spawn.

**Comment by FavouriteDragon** [comment]
1) Fair enough- I haven't readded waterbending, icebending, or made lightningbending good yet lol.
2) Yeah just specify that on your modpack (still list my mod as a dependency, just clarify in your description; don't distribute it outside of the modpack, please and thank  you).
3) Yeah the mob config for 1.5.17 isn't exactly good. You may have to wait for more stable 1.6.0 updates :P

**Comment by wolfkidsounds** [comment]
Thank you very much. After I'm done with this specific server pack i would like to create a avatar modpack focusing on this mod.

Are there any things i could help improving? I really have a hard time learning to code at the moment (Java) but maybe i can still be

**Comment by FavouriteDragon** [comment]
Uh for 1.6.0 if you could help with mob optimisation, that'd be pretty nice! Actually, can you use 1.6.0-alpha.14, make some mobs fight with bending, and give me a tick report? Thank you!
And awesome!
