### ISSUE TITLE
Mine Blocks not triggering block updates

### ISSUE THREAD

**Issue by Sarous** [ProjectKorra/AvatarMod#245]
When using Mine Blocks, it does not appear to be triggering the normal block update event. Things which are attached to, growing on, or otherwise dependent upon a block which is mined are not collapsing when the host block is mined.

Sand on top of a mined block is left levitating.
Grass and plants above a mined block likewise levitate.
Torches attacked to mined blocks do not fall to the ground.

Alpha-14

**Comment by FavouriteDragon** [comment]
Why are we here
Just to suffer?

**Comment by FavouriteDragon** [comment]
Ok fixed this, it'll be in the next update.
