### ISSUE TITLE
what how

### ISSUE THREAD

**Issue by thewhen** [ProjectKorra/AvatarMod#246]
Alright, so
I have a premium account and all of that, using the official launcher, the correct mods, the right version (yes I checked and I'm using Forge)
The problem is, when I sit on a Bison, I'm not only sitting on it, but I'm sitting on it with a three blocks distance between my avatar and the Bison
so pl eas e h elp i n eed hel p
Ok thanks for reading this but I think that you already know about this problem or someone else told you

**Comment by FavouriteDragon** [comment]
1.5.17, yeah? Should already be fixed
