### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by Dragonking4800** [ProjectKorra/AvatarMod#248]
Hi im trying to play on a server with a friend but every time i add Optifine the screen justlooks like this
![Base Profile Screenshot 2021 04 24 - 12 19 06 52](https://user-images.githubusercontent.com/83117966/115955551-6bf49300-a4f7-11eb-8b10-b5ba9aeedd2f.png)

**Comment by Mahtaran** [comment]
Hi, I am closing this since it is missing a lot of necessary information, such as logs, game version, Java version, the type of server, et cetera. Feel free to reopen it when you have added this information.
