### ISSUE TITLE
Adding multiple bendings

### ISSUE THREAD

**Issue by zero4089** [ProjectKorra/AvatarMod#249]
I am playing in a survival world, and I unlocked airbending with a scroll, but now I have a firebending scroll and want to add fire bending. When I right click on the scroll, it just brings me to the airbending menu where you can unlock new skills. I'm playing on a world with no cheats on, and I have a ton of firebending scrolls already, so I don't really want to start over with cheats on

**Comment by Mahtaran** [comment]
[The temporary way](https://nerdburglars.net/question/can-you-enable-cheats-in-an-existing-world/)
[The permanent way](http://thecomputerblog.net/enable-cheats-already-existing-world-minecraft/)
