### ISSUE TITLE
Incompatibility with Construct's Armory

### ISSUE THREAD

**Issue by AugmentedSmurf** [ProjectKorra/AvatarMod#251]
Any time you open one of Construct's Armory Armor Stations, it crashes the client all the way to desktop due to a UUID/GUI error.

[Crash Report](https://paste.ee/p/Lrs6f)

Not sure if this is your issue or ConArm's, but I'll post it both places.

**Comment by FavouriteDragon** [comment]
Ope paste is gone; please reupload
