### ISSUE TITLE
my changes in the config file arent permanent

### ISSUE THREAD

**Issue by Daggaron** [ProjectKorra/AvatarMod#258]
I'm trying to play this mod on a server I host and we want to disable the cooldowns, but when I edit the ability files in the config, the server resets the files and the changes become undone. when the server is already running and I try to edit the config (and use the command /avatar config) the changes won't go into effect

what can i do to disable the cooldowns?

**Comment by FavouriteDragon** [comment]
Mod version? Did you disable ignoring the config for both client and server?

**Comment by FavouriteDragon** [comment]
No followup.
