### ISSUE TITLE
crashes whenever i try to play 

### ISSUE THREAD

**Issue by Chaotic02** [ProjectKorra/AvatarMod#262]
whenever i try to play with this mod installed, it crashes my game

**Comment by xXMrBlueXx** [comment]
my friends works because he pressed the send feedback button, and i pressed dont do that on mine, are the devs of this mod really that petty?

**Comment by xXMrBlueXx** [comment]
yeah so i just uninstalled minecraft and re installed it and clicked send feedback and it worked, these devs are that petty

**Comment by FavouriteDragon** [comment]
What? We don't get feedback when you press "send feedback". We're not part of Mojang's database. Provide the crash reports or kindly stop being wankers and screw off.
