### ISSUE TITLE
Fireball stuck to my face!

### ISSUE THREAD

**Issue by omegadmm** [ProjectKorra/AvatarMod#27]
I just recently discovered that if I double click (I bound the attack to my mouse 5 button) the fireball ability, it will unhook the first fireball and go into the second fireball. Meaning I am stuck with a fireball floating in my face unless I look down at the ground to cause it to go off.
Minecraft 1.12.1
Forge: 14.22.1.2485
Edit: Seems to happen with the Fire Arc as well. I think it may be an issue with mouse assignment altogether.

**Comment by CrowsOfWar** [comment]
Are you able to create multiple fireballs at once?

**Comment by omegadmm** [comment]
When this issue occurred, I technically did. It did show two of them any time I reactivated the ability and only one of the two would launch. Although the buggy one was active as I tested it by launching the second sphere then with the buggy one still there I looked down and boom. So not an graphical artifact xD.

**Comment by FavouriteDragon** [comment]
Fixed! Sorry it took me so long!

**Comment by FavouriteDragon** [comment]
Fixed! Sorry it took me so long!
