### ISSUE TITLE
Mouse key binding issue.

### ISSUE THREAD

**Issue by omegadmm** [ProjectKorra/AvatarMod#28]
When I key bind my mouse buttons to say the fireball, save and restart the game. I lose that binding.
Minecraft 1.12.1
Forge: 14.22.1.2485
Mod: avatarmod-a4.6

**Comment by FavouriteDragon** [comment]
hmm
Try updating and see if it still happens

**Comment by omegadmm** [comment]
I tested 5.3 and it is holding the bindings now. Sorry about getting back so late, I've been "out of the scene".

**Comment by omegadmm** [comment]
Well I just got back on after two days and the bindings are not active again.

**Comment by FavouriteDragon** [comment]
Hmm that's weird!
-What forge version are you using?
-Are you on singplayer? Multiplayer? A LAN network???

**Comment by omegadmm** [comment]
I am running single player and am using Forge with Liteloader, but no keymapping mods. 
1.12.2-LiteLoader1.12.2-1.12.2-forge1.12.2-14.23.4.2705

**Comment by FavouriteDragon** [comment]
Try downgrading to forge version 1.12.2-14.23.4.2611 or 2555!
Also, if that doesn't work, try removing LiteLoader.

**Comment by FavouriteDragon** [comment]
Ok tested it out myself- Definitely a bug. Gonna bet mahtaran to look at it while I'm gone.

**Comment by Ragnurhelgon** [comment]
Did that ever get patched? Because I'm facing the same issue.

**Comment by Mahtaran** [comment]
Known bug.
