### ISSUE TITLE
I cant unlock or use any type of bending.

### ISSUE THREAD

**Issue by BeardStroker** [ProjectKorra/AvatarMod#40]
Minecraft 1.12.2
Forge: 14.23.1.2560
avatarmod-a5.0_preview1.jar (had the same issue on the previous version)

This was all tested on both a big modpack and a fresh world with only the Avatar mod and forge installed.

I have a issue where no matter what I do, I cant unlock and use any type of bending.
I have tried using the skill menu where you add 3 scrolls to unlock bending, but after I choose earthbending I can't unlock any abilities. If I click any of them and add a scroll, and then press unlock the scroll just disappears and the skill tree does not show up. If I add another scroll it just stays in the slot when I press unlock. After doing this when I press "use bending" it says in chat that I have not learned any bending yet and to use the /Avatar commands to add bending. 

So I tried using the /avatar commands to add another type of bending but it's the same result. Same if I add them all. The wheel menu where I am supposed to scroll between earth, fire and so on does not show up either, and the skill menu only opens the last bending that was added, and sometimes it does not open the menu at all. If I try to use bending after all this it still says I don't know any bending.

I have tried the mod before in a4.6, but that was using a modpack with a outdated forge version and then it actually worked, except for a couple of bugs where the flamethrower was invisible and the dig blocks just cloned blocks and did not make holes, so maybe it's a forge version issue?

Anyway, I love the concept of the mod and would love to use it, but at the moment nothing works for me with the current forge and a4.6 OR a5.0. If you need any information from me that could help fix this issue I would be happy to supply it. Keep up the good work! :)

**Comment by CrowsOfWar** [comment]
Hey, I'm sorry to hear you're having problems with the avatar mod. I just tested this out myself and unlocking abilities seems to be working, which is really strange. Is it possible that you are using a cracked account? There have been issues with this in the past, and although it's supposed to work there are occasionally problems with that. There are other possibilities but that would be my first guess.

**Comment by BeardStroker** [comment]
Nope, my account is 100% legit and I have used it for years :) I checked what forge version the modpack I first added your mod to was running, and tested the newest update on it 14.23.0.2512. The newest update works fine on it and even the bugs I experienced on the last version are fixed so that's nice :) 
Just to make sure I tested on a vanilla world with the same forge version and it works fine. 
So it definitely seems to me like it just does not work on the newest forge version.

**Comment by CrowsOfWar** [comment]
Okay, I'm glad to hear that you found a workaround for now. That's very weird though, and now that you mentioned that changing the Forge version fixes it, I've downloaded the latest version as well and it seems there is an issue. I'm investigating and will let you know what I find

**Comment by CrowsOfWar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [MAJOR bending issues on latest Forge veersion](https://trello.com/c/m6hgI5X8/416-major-bending-issues-on-latest-forge-veersion)

**Comment by BeardStroker** [comment]
Awesome, thanks for looking into it. Would love to use the mod on my current up to date world, especially with all the cool stuff that is getting added :)

**Comment by CrowsOfWar** [comment]
Alright, looks like I found the problem! It had to do with a difference in Forge code between 2491 and 2555.

The attached jar should be working, just unzip and enjoy :) But if not let me know!
[avatarmod-a5.0.jar.zip](https://github.com/ProjectKorra/AvatarMod/files/1557849/avatarmod-a5.0.jar.zip)

**Comment by BeardStroker** [comment]
Works great with Forge: 14.23.1.2566 now :) Thanks for fixing it! Looking forward to test out the new abilities. Good luck with further development, and I'll try to give some feedback after testing it out more :)
