### ISSUE TITLE
Crash in Creative Mode after using Universal Scroll

### ISSUE THREAD

**Issue by HyperMan19680** [ProjectKorra/AvatarMod#42]
https://www.dropbox.com/s/mavefvnfvprijl8/crash-2018-01-03_10.19.39-client.txt?dl=0 is the crash log I had when I used one after unlocking my bending.

**Comment by Sehyan** [comment]
Same problem here, with the newest a5.0 version. Game crashes after using any scroll after having unlocked a bending technique.
Tried adding more ram, playing with and without other mods, creative and survival, reinstalling newest versions of java & forge, to no avail.

The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Problem getting width of earthbending background image

[crashlog, dropbox](https://www.dropbox.com/s/ff1ft8ex7o5gmyg/crash-2018-01-03_19.44.54-client.txt?dl=0)

Love the other versions though, thanks!

**Comment by CrowsOfWar** [comment]
Thanks for the crash report guys. Looks like it was a mistake on our part. Anyways, here is the fixed version, I've tested it and it should work!! Thanks for letting us know!

https://minecraft.curseforge.com/projects/avatar-mod-2-out-of-the-iceberg/files/2516280

if link doesn't work check again in 10 minutes

**Comment by Sehyan** [comment]
Thanks so much! Looking forward to playing the mod 👍 :)
