### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Mo-og** [ProjectKorra/AvatarMod#43]
Mod  v. a5.0 to a.5.1 crashes servers. Tried Forge versions 14.23.1.2585 and 14.23.1.2555 with and without other mods, but it gives an error. If I run the mod on client, it works well. Here`s a report.
[crash-2018-01-07_23.30.43-server.txt](https://github.com/ProjectKorra/AvatarMod/files/1610213/crash-2018-01-07_23.30.43-server.txt)

**Comment by CrowsOfWar** [comment]
Thanks for the bug report. It looks like an issue where one of the software components Avatar Mod uses on is broken on servers. I'll take a look at it.
