### ISSUE TITLE
Typo in .lang file +

### ISSUE THREAD

**Issue by Mo-og** [ProjectKorra/AvatarMod#44]
Instead of "avatar.combustionbending.de**m**onym",
"avatar.combustionbending.de**n**onym" is written. So it causes wrong chat message when you become a combustionbender through command. And it`s not only in english .lang file, unfortunately.

I`d also like to add my translation file for Russian language. Let it be both here and on trello. 
[ru_RU.zip](https://github.com/ProjectKorra/AvatarMod/files/1695425/ru_RU.zip)

P.S. There are no "Performance" and "PowerRating" lines in the .lang file.

**Comment by Mahtaran** [comment]
Should be fixed in #61
