### ISSUE TITLE
Server not recognizing as mod.

### ISSUE THREAD

**Issue by 2ndParty** [ProjectKorra/AvatarMod#45]
Minecraft 1.12
Forge 14.21.1.2428
CubedHost server

[WARN] Zip file avatarmod-a5.1.jar failed to read properly, it will be ignored
[INFO] FML has found a non-mod file avatarmod-a5.1.jar in your mods directory.

Not sure what to do to get this mod running properly on my server.

**Comment by CrowsOfWar** [comment]
Thanks for letting me know, it's an issue on our end. I've got a fix for it
and I'll try to get it out tonight.

**Comment by CrowsOfWar** [comment]
Okay, if you download this next version alpha 5.2, it should fix your problem. Thanks for your patience!

https://minecraft.curseforge.com/projects/avatar-mod-2-out-of-the-iceberg/files/2522434
