### ISSUE TITLE
Big problems 

### ISSUE THREAD

**Issue by Copyrighteous** [ProjectKorra/AvatarMod#46]
I played with my friend on a LAN world in witch he would host. The mod worked fine while we played, but after we got off the world all of are bending moves where deleted. We thought it was keep Inventory because we had it set to true. So we made a new word and and when we go t back on it after getting of Minecraft the world was gone. I don't know if it is another mod doing it. 

Mod list used: Avatar 2: out of the iceberg, mod dismemberment, recurrent complex, spartan shields, spartan weaponry, and just enough items.

**Comment by FavouriteDragon** [comment]
Hmmm
-What forge version were you using?
-What mod version were you using?

**Comment by FavouriteDragon** [comment]
@Copyrighteous

**Comment by Copyrighteous** [comment]
The newest version I think

**Comment by Copyrighteous** [comment]
forge 14.23.2.2613

**Comment by FavouriteDragon** [comment]
Ok so this happens when your server is set to offline mode @Copyrighteous , and we don't support offline mode. We also don't support cracked accounts.
