### ISSUE TITLE
[Suggestion] Replace server cache file with usernamecache.json

### ISSUE THREAD

**Issue by Mahtaran** [ProjectKorra/AvatarMod#52]
Currently in [AccountUUIDs](https://github.com/ProjectKorra/AvatarMod/blob/master/src/main/java/com/crowsofwar/gorecore/util/AccountUUIDs.java) you use a new cache file named "GoreCore_ServerUUIDCache.txt". However, every server already has a "usernamecache.json" which is exactly the same thing but from UUID to username instead of username to UUID. My suggestion is to remove the "GoreCore_ServerUUIDCache.txt" and use "usernamecache.json", something I can implement unless @CrowsOfWar knows something I'm overlooking.

**Comment by Mahtaran** [comment]
@CrowsOfWar _bump_

**Comment by CrowsOfWar** [comment]
@Mahtaran good idea, it looks like the GoreCore cache is unnecessary. 

I'm not at my computer right now, but I did a bit of research and maybe the pre-existing class `net.minecraftforge.common.UsernameCache` might work? This could potentially be useful to avoid manually reading and parsing the json file. Of course if you were planning on parsing it yourself, that could be a good approach too.
