### ISSUE TITLE
[Suggestion] Support for Biomes O Plenty Blocks / [Bug] Key Bindings Disappearing

### ISSUE THREAD

**Issue by Burgersim** [ProjectKorra/AvatarMod#77]
I wanted to ask if this was in any way possible, because I saw that in a BOP world, where the different kind of dirts generate I couldn't use earthbending on those blocks.

The other thing friends and I noticed is that on our SMP Server the Key Bindings in the Skils Menu have to be reassigned everytime you start the Game anew, is that a known bug, or are we doing anything wring maybe?

**Comment by FavouriteDragon** [comment]
As far as I know, if using the config doesn't work, it's not possible, as Biomes o Plenty or I would have to mess with mod loading order.
What version of the mod are you using?
What version of forge?

**Comment by Burgersim** [comment]
Forge 14.23.3.2675
Avatar Mod a5.2
BOP 7.0.1

So it would be possible to add blocks via the config? 

I just thought, wouldn't it maybe be possible to use oredict entries for determining the blocks? I don't know a lot about this stuff, but like saying, everything that is registered as block:dirt or sthg like that can be earthbended?

**Comment by FavouriteDragon** [comment]
Try downgrading to 14.23.3.2611 or 2555.
Also try using a5.3.

Yes, it's possible. Yes, everything that has block:dirt as its name can be bent (bended?).

**Comment by FavouriteDragon** [comment]
@Burgerism
Try seeing if it works with the latest updates 
It should work

**Comment by FavouriteDragon** [comment]
The blocks thing should, anyway

**Comment by Aang23** [comment]
I did test and it works, at least for me.

**Comment by Mahtaran** [comment]
Suggestion is implemented, bug is known. Therefore, I will close this now.
