### ISSUE TITLE
Heavy Immobile GUI elements reduce compatability

### ISSUE THREAD

**Issue by Divineaspect** [ProjectKorra/AvatarMod#83]
This Mod has a lot of heavy GUI indicators who can't have their position changed.
The element indicator doesn't need to be up constantly, most people pick one element, and the wheel has backgrounds for a reason, also the icons are generally very clear in what they indicate.

The Chi bar? on the lower left is confusing especially with the The numeric indicators are on the upper right

I do like the ready to use indicator for my air leap which is a temporary icon near the targeting reticule.

I can imagine lots of potential solutions if you want them proposed.

**Comment by Divineaspect** [comment]
a config or command to reposition  the gui is good
a user config for fading out when you're normal is also good.

**Comment by FavouriteDragon** [comment]
Well I've got some config in place for this. Not nearly as extensive as I'd like, but it works for now.

**Comment by FavouriteDragon** [comment]
Ok, did a decent temp fix for now- the chi bar is now on the right, more transparent, and the config actually works xD
