### ISSUE TITLE
NPE Crash on Game Load

### ISSUE THREAD

**Issue by WenXin20** [ProjectKorra/AvatarMod#85]
Forge v14.23.4.2750-1.12.2
Avatar va5.6

I get this crash on game launch. 
Here's the [crash report](https://paste.dimdev.org/payuticosu.mccrash
).

**Comment by FavouriteDragon** [comment]
What exactly did you do? Sorry for not responding earlier! Any other mods? Do you have a cracked account? Did you not set the game language?

**Comment by FavouriteDragon** [comment]
What is editing your language?

**Comment by WenXin20** [comment]
It's definitely not a cracked account. I think it was a either a bad forge or minecraft launcher version, because after updating forge, I didn't get the crash again.

**Comment by FavouriteDragon** [comment]
Hmm ok!
