### ISSUE TITLE
Some things

### ISSUE THREAD

**Issue by Mo-og** [ProjectKorra/AvatarMod#95]
First, I am reposting the translation here, as it seems not to be updated if  it is on Trello only:

https://trello-attachments.s3.amazonaws.com/588d51b172bda0848cc86c90/592cd06b7f8e04237785b74b/ba19aa5a4cfe4f67e39a9c6e04422e7e/ru_RU.lang

Second, the scrolling in Bending Menu (screen.) seems to be unlimited. It`s not a problem, though abilities can go far beyond the screen sometimes.
![Menu](https://user-images.githubusercontent.com/26124396/47050582-95573a00-d1a9-11e8-9074-3bc18110f405.png)

And third, I don`t like the menu background for airbending, so here are my screenshots for it :-) 
![airbending](https://user-images.githubusercontent.com/26124396/47050648-da7b6c00-d1a9-11e8-83b1-eb5a52f35536.png)
![1airbending](https://user-images.githubusercontent.com/26124396/47050649-da7b6c00-d1a9-11e8-8988-6a8aaa928885.png)
Thank you for developing the mod!

**Comment by FavouriteDragon** [comment]
Huh that's super weird!
And the translation used the latest changes from a5.9.2, right?
Thanks!
Hmmm how about just a shot of a sky bison flying in clouds?
For the Airbending background

**Comment by Mo-og** [comment]
Yeah, the translation uses a5.9.2 changes. And I even tried to make this lines
![ability locked](https://user-images.githubusercontent.com/26124396/47106394-0f8dca00-d24f-11e8-8efe-4f10172d4031.png)
look like this:
![ability locked(1)](https://user-images.githubusercontent.com/26124396/47106530-78754200-d24f-11e8-8d47-189b02aca69d.png)

By the way, they look different if you resize game`s window:
![unmodified variant](https://user-images.githubusercontent.com/26124396/47106648-d6098e80-d24f-11e8-89da-a086c34cab95.png)

And a few screenshots.
![This is probably the one you wanted](https://user-images.githubusercontent.com/26124396/47108255-e28fe600-d253-11e8-8732-9dc78fb871a7.png)
![2018-10-17_20 25 59](https://user-images.githubusercontent.com/26124396/47108455-6053f180-d254-11e8-9176-dbbba096707b.png)
![2018-10-17_20 27 11](https://user-images.githubusercontent.com/26124396/47108456-60ec8800-d254-11e8-8bf6-3540363cd778.png)

**Comment by FavouriteDragon** [comment]
Ok cool!
Do you mind also editing the English lang file so it does what you're trying to do? 
Thanks!

**Comment by FavouriteDragon** [comment]
Hmm can you get way more clouds?
And maybe a mountain backdrop hiding behind the clouds?

**Comment by Mo-og** [comment]
I corrected text format by resetting it with [yellow][/yellow] in two lines. Though it should be done in other way, I think. 
[en_us.txt](https://github.com/ProjectKorra/AvatarMod/files/2497172/en_us.txt)
![screenshot_379130718000000](https://user-images.githubusercontent.com/26124396/47234958-23b50100-d3e0-11e8-9460-f8e06c4c5e33.png)
It seems like '§' operators were supposed to work for a single word, but they work till the end of line instead.

Making terrain hide behind the clouds is only possible if they are vanilla ones, but they are either black or transparent if I use shaders.
Like that without shaders:
![2018-10-19_20 56 31](https://user-images.githubusercontent.com/26124396/47240240-70a0d380-d3f0-11e8-9311-93833bddce06.png)
With them and clouds:
![2018-10-19_18 49 00](https://user-images.githubusercontent.com/26124396/47240328-a80f8000-d3f0-11e8-9428-b2da232822f3.png)
![2018-10-19_18 45 14](https://user-images.githubusercontent.com/26124396/47240308-9af29100-d3f0-11e8-9744-7b74d7615d17.png)
Without vanilla clouds
![2018-10-18_00 36 49](https://user-images.githubusercontent.com/26124396/47240450-03da0900-d3f1-11e8-9bbe-3ca35545df87.png)
![2018-10-18_00 40 09](https://user-images.githubusercontent.com/26124396/47240463-0ccada80-d3f1-11e8-8ba2-ab0351e32574.png)
![2018-10-18_00 41 06](https://user-images.githubusercontent.com/26124396/47240477-194f3300-d3f1-11e8-8ec2-531eb184b523.png)
![2018-10-19_21 51 28](https://user-images.githubusercontent.com/26124396/47240670-c88c0a00-d3f1-11e8-9fa8-40095989a74b.png)
![2018-10-19_22 31 53](https://user-images.githubusercontent.com/26124396/47240797-1dc81b80-d3f2-11e8-807e-cff8fd1ae201.png)

**Comment by FavouriteDragon** [comment]
Ok so those screenshots are heckin' beautiful!
Hmm
Maybe just a screenshot of some super thick clouds with the shadow of a bison?
You're looking upwards, so you don't see any mc terrain?

**Comment by Mo-og** [comment]
Shader's clouds are just a picture and I can't get higher than it. If I use vanilla clouds I won't get shadow on them either, because clouds are black, sorry.
If clouds are made of concrete though, we get this:
![2018-10-20_13 12 26](https://user-images.githubusercontent.com/26124396/47255150-13029a80-d475-11e8-9b46-d9047e3bf8f0.png)
![2018-10-20_13 36 39](https://user-images.githubusercontent.com/26124396/47255151-13029a80-d475-11e8-9bc6-a9260eddc5d0.png)
![2018-10-20_13 42 20](https://user-images.githubusercontent.com/26124396/47255152-139b3100-d475-11e8-94eb-80f30330f6fb.png)

**Comment by Mo-og** [comment]
No way. Even when I got shader with real volumetric clouds, nothing can cast shadow on them. 
![2018-10-20_21 19 48](https://user-images.githubusercontent.com/26124396/47259241-685b9d80-d4af-11e8-93f5-8a2bc2cd6a37.png)
![2018-10-20_21 22 13](https://user-images.githubusercontent.com/26124396/47259242-685b9d80-d4af-11e8-893b-2f234d29f2aa.png)
![2018-10-20_21 22 49](https://user-images.githubusercontent.com/26124396/47259243-685b9d80-d4af-11e8-975e-ffcff6857165.png)

**Comment by Mo-og** [comment]
Oops

**Comment by FavouriteDragon** [comment]
Ok that first screenshot of the 3 you just posted is perfect!

**Comment by FavouriteDragon** [comment]
Yessss

**Comment by FavouriteDragon** [comment]
Ok so a5.9.2 Preview 3 has the new screenshot and the new translation; the gui bug isn't really major, nor will it happen a lot
