### ISSUE TITLE
[Suggestion] Effects with Water Bending

### ISSUE THREAD

**Issue by Xion-Loves-Disney** [ProjectKorra/AvatarMod#96]
First of all, I don't want to come off as demanding. This is only a suggestion to be considered.

My friends and I were playing with this mod and BOP, as we are all fans of Avatar. However, something that kind of bugged us was that a water bender was able to breathe underwater and that they could mine fast underwater. To us, having those effects take away from the surviving aspect of the game. Maybe they could be removed, at least in one form of the game for 1.12.2? I know you worked very hard on this, so I hate asking this. Other than that, we love the mod. 

Keep up the amazing work!

**Comment by FavouriteDragon** [comment]
Thanks!
Hmmm....
We can add a config for potion effects for each element, and whether to even use effects as passives.

**Comment by Xion-Loves-Disney** [comment]
Yeah, something like that could work. You can make it an option for play, thus people can still use the effects if they want to. Plus, you can still use all of your hard work.

**Comment by FavouriteDragon** [comment]
Yep!
In the future, I'll think it won't be as much of a problem- potion effect passives, and other passives, will be locked in a skill tree for each element.
Thanks! 
Crows and Mahtaran did most of it, though :P

**Comment by Xion-Loves-Disney** [comment]
Ok, and no problem! Tell them that my friends and  I appreciate their work!

**Comment by Mahtaran** [comment]
Well, we appreciate you too for playing the mod! A configuration option for a feature like this would definitely be possible. Added to the to-do list for version 1.6.0-alpha!

**Comment by FavouriteDragon** [comment]
Done!
Well, not quite what I'm going for, but it adds options for all current passive potion effects.
