### ISSUE TITLE
Abilities` interaction with cobweb

### ISSUE THREAD

**Issue by Mo-og** [ProjectKorra/AvatarMod#98]
Most abilities\` projectiles should either break cobwebs or at least pass through them, but they get stuck instead (thanks, Minecraft). And it`s especially strange when you do firebending. 
Moreover, there is a bug with ravine. When it passes through 1/2 of block near the cobweb it gets stuck in place and continues working.

https://youtu.be/3zkpHkddOcU

**Comment by FavouriteDragon** [comment]
xD That's not good!
I'll fix this next week when I get back.

**Comment by FavouriteDragon** [comment]
Fixed
Will be uploaded with the next update
